// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base/base.proto

package com.bytedanceapi.model.common;

public final class Base {
  private Base() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(Base.productType);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int PRODUCT_TYPE_FIELD_NUMBER = 10000;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.String> productType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vcloud_Models_Base_ResponseMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Vcloud_Models_Base_ResponseMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vcloud_Models_Base_ResponseError_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Vcloud_Models_Base_ResponseError_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017base/base.proto\022\022Vcloud.Models.Base\032 g" +
      "oogle/protobuf/descriptor.proto\"\231\001\n\020Resp" +
      "onseMetadata\022\021\n\tRequestId\030\001 \001(\t\022\016\n\006Actio" +
      "n\030\002 \001(\t\022\017\n\007Version\030\003 \001(\t\022\017\n\007Service\030\004 \001(" +
      "\t\022\016\n\006Region\030\005 \001(\t\0220\n\005Error\030\006 \001(\0132!.Vclou" +
      "d.Models.Base.ResponseError\".\n\rResponseE" +
      "rror\022\014\n\004Code\030\001 \001(\t\022\017\n\007Message\030\002 \001(\t:6\n\014p" +
      "roduct_type\022\034.google.protobuf.FileOption" +
      "s\030\220N \001(\t\210\001\001B\224\001\n\035com.bytedanceapi.model.c" +
      "ommonB\004BaseP\001Z1github.com/volcengine/vol" +
      "c-sdk-golang/models/base\240\001\001\330\001\001\302\002\000\312\002\022Vclo" +
      "ud\\Models\\Base\342\002\031Vcloud\\Models\\GPBMetada" +
      "tab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_Vcloud_Models_Base_ResponseMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Vcloud_Models_Base_ResponseMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Vcloud_Models_Base_ResponseMetadata_descriptor,
        new java.lang.String[] { "RequestId", "Action", "Version", "Service", "Region", "Error", });
    internal_static_Vcloud_Models_Base_ResponseError_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Vcloud_Models_Base_ResponseError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Vcloud_Models_Base_ResponseError_descriptor,
        new java.lang.String[] { "Code", "Message", });
    productType.internalInit(descriptor.getExtensions().get(0));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
