// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod_media.proto

package com.bytedanceapi.model.common;

/**
 * Protobuf type {@code Vcloud.Models.Vod.BasicInfo}
 */
public final class BasicInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Vcloud.Models.Vod.BasicInfo)
    BasicInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BasicInfo.newBuilder() to construct.
  private BasicInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BasicInfo() {
    spaceName_ = "";
    vid_ = "";
    title_ = "";
    description_ = "";
    posterUri_ = "";
    publishStatus_ = "";
    tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    createTime_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new BasicInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BasicInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            spaceName_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            vid_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            posterUri_ = s;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            publishStatus_ = s;
            break;
          }
          case 56: {

            auditStatus_ = input.readInt64();
            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              tags_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            tags_.add(s);
            break;
          }
          case 74: {
            String s = input.readStringRequireUtf8();

            createTime_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        tags_ = tags_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return VodMedia.internal_static_Vcloud_Models_Vod_BasicInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return VodMedia.internal_static_Vcloud_Models_Vod_BasicInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BasicInfo.class, Builder.class);
  }

  public static final int SPACENAME_FIELD_NUMBER = 1;
  private volatile Object spaceName_;
  /**
   * <pre>
   *空间名
   * </pre>
   *
   * <code>string SpaceName = 1;</code>
   * @return The spaceName.
   */
  @Override
  public String getSpaceName() {
    Object ref = spaceName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      spaceName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *空间名
   * </pre>
   *
   * <code>string SpaceName = 1;</code>
   * @return The bytes for spaceName.
   */
  @Override
  public com.google.protobuf.ByteString
      getSpaceNameBytes() {
    Object ref = spaceName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      spaceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VID_FIELD_NUMBER = 2;
  private volatile Object vid_;
  /**
   * <pre>
   *视频ID
   * </pre>
   *
   * <code>string Vid = 2;</code>
   * @return The vid.
   */
  @Override
  public String getVid() {
    Object ref = vid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      vid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *视频ID
   * </pre>
   *
   * <code>string Vid = 2;</code>
   * @return The bytes for vid.
   */
  @Override
  public com.google.protobuf.ByteString
      getVidBytes() {
    Object ref = vid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      vid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  private volatile Object title_;
  /**
   * <pre>
   *视频名称
   * </pre>
   *
   * <code>string Title = 3;</code>
   * @return The title.
   */
  @Override
  public String getTitle() {
    Object ref = title_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *视频名称
   * </pre>
   *
   * <code>string Title = 3;</code>
   * @return The bytes for title.
   */
  @Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    Object ref = title_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  private volatile Object description_;
  /**
   * <pre>
   *视频描述
   * </pre>
   *
   * <code>string Description = 4;</code>
   * @return The description.
   */
  @Override
  public String getDescription() {
    Object ref = description_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *视频描述
   * </pre>
   *
   * <code>string Description = 4;</code>
   * @return The bytes for description.
   */
  @Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    Object ref = description_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSTERURI_FIELD_NUMBER = 5;
  private volatile Object posterUri_;
  /**
   * <pre>
   *封面图对象地址
   * </pre>
   *
   * <code>string PosterUri = 5;</code>
   * @return The posterUri.
   */
  @Override
  public String getPosterUri() {
    Object ref = posterUri_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      posterUri_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *封面图对象地址
   * </pre>
   *
   * <code>string PosterUri = 5;</code>
   * @return The bytes for posterUri.
   */
  @Override
  public com.google.protobuf.ByteString
      getPosterUriBytes() {
    Object ref = posterUri_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      posterUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PUBLISHSTATUS_FIELD_NUMBER = 6;
  private volatile Object publishStatus_;
  /**
   * <pre>
   *发布状态
   * </pre>
   *
   * <code>string PublishStatus = 6;</code>
   * @return The publishStatus.
   */
  @Override
  public String getPublishStatus() {
    Object ref = publishStatus_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      publishStatus_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *发布状态
   * </pre>
   *
   * <code>string PublishStatus = 6;</code>
   * @return The bytes for publishStatus.
   */
  @Override
  public com.google.protobuf.ByteString
      getPublishStatusBytes() {
    Object ref = publishStatus_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      publishStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUDITSTATUS_FIELD_NUMBER = 7;
  private long auditStatus_;
  /**
   * <pre>
   *审核状态
   * </pre>
   *
   * <code>int64 AuditStatus = 7;</code>
   * @return The auditStatus.
   */
  @Override
  public long getAuditStatus() {
    return auditStatus_;
  }

  public static final int TAGS_FIELD_NUMBER = 8;
  private com.google.protobuf.LazyStringList tags_;
  /**
   * <pre>
   *标签列表
   * </pre>
   *
   * <code>repeated string Tags = 8;</code>
   * @return A list containing the tags.
   */
  public com.google.protobuf.ProtocolStringList
      getTagsList() {
    return tags_;
  }
  /**
   * <pre>
   *标签列表
   * </pre>
   *
   * <code>repeated string Tags = 8;</code>
   * @return The count of tags.
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <pre>
   *标签列表
   * </pre>
   *
   * <code>repeated string Tags = 8;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  public String getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <pre>
   *标签列表
   * </pre>
   *
   * <code>repeated string Tags = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  public com.google.protobuf.ByteString
      getTagsBytes(int index) {
    return tags_.getByteString(index);
  }

  public static final int CREATETIME_FIELD_NUMBER = 9;
  private volatile Object createTime_;
  /**
   * <pre>
   *创建时间
   * </pre>
   *
   * <code>string CreateTime = 9;</code>
   * @return The createTime.
   */
  @Override
  public String getCreateTime() {
    Object ref = createTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      createTime_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *创建时间
   * </pre>
   *
   * <code>string CreateTime = 9;</code>
   * @return The bytes for createTime.
   */
  @Override
  public com.google.protobuf.ByteString
      getCreateTimeBytes() {
    Object ref = createTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      createTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSpaceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, spaceName_);
    }
    if (!getVidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, vid_);
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, title_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
    }
    if (!getPosterUriBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, posterUri_);
    }
    if (!getPublishStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, publishStatus_);
    }
    if (auditStatus_ != 0L) {
      output.writeInt64(7, auditStatus_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tags_.getRaw(i));
    }
    if (!getCreateTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, createTime_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSpaceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, spaceName_);
    }
    if (!getVidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, vid_);
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, title_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
    }
    if (!getPosterUriBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, posterUri_);
    }
    if (!getPublishStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, publishStatus_);
    }
    if (auditStatus_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, auditStatus_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tags_.size(); i++) {
        dataSize += computeStringSizeNoTag(tags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagsList().size();
    }
    if (!getCreateTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, createTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BasicInfo)) {
      return super.equals(obj);
    }
    BasicInfo other = (BasicInfo) obj;

    if (!getSpaceName()
        .equals(other.getSpaceName())) return false;
    if (!getVid()
        .equals(other.getVid())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getPosterUri()
        .equals(other.getPosterUri())) return false;
    if (!getPublishStatus()
        .equals(other.getPublishStatus())) return false;
    if (getAuditStatus()
        != other.getAuditStatus()) return false;
    if (!getTagsList()
        .equals(other.getTagsList())) return false;
    if (!getCreateTime()
        .equals(other.getCreateTime())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SPACENAME_FIELD_NUMBER;
    hash = (53 * hash) + getSpaceName().hashCode();
    hash = (37 * hash) + VID_FIELD_NUMBER;
    hash = (53 * hash) + getVid().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + POSTERURI_FIELD_NUMBER;
    hash = (53 * hash) + getPosterUri().hashCode();
    hash = (37 * hash) + PUBLISHSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + getPublishStatus().hashCode();
    hash = (37 * hash) + AUDITSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAuditStatus());
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
    hash = (53 * hash) + getCreateTime().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BasicInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BasicInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BasicInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BasicInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BasicInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BasicInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BasicInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BasicInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static BasicInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static BasicInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BasicInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BasicInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BasicInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Vcloud.Models.Vod.BasicInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Vcloud.Models.Vod.BasicInfo)
      BasicInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VodMedia.internal_static_Vcloud_Models_Vod_BasicInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VodMedia.internal_static_Vcloud_Models_Vod_BasicInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BasicInfo.class, Builder.class);
    }

    // Construct using com.bytedanceapi.model.common.BasicInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      spaceName_ = "";

      vid_ = "";

      title_ = "";

      description_ = "";

      posterUri_ = "";

      publishStatus_ = "";

      auditStatus_ = 0L;

      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      createTime_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return VodMedia.internal_static_Vcloud_Models_Vod_BasicInfo_descriptor;
    }

    @Override
    public BasicInfo getDefaultInstanceForType() {
      return BasicInfo.getDefaultInstance();
    }

    @Override
    public BasicInfo build() {
      BasicInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public BasicInfo buildPartial() {
      BasicInfo result = new BasicInfo(this);
      int from_bitField0_ = bitField0_;
      result.spaceName_ = spaceName_;
      result.vid_ = vid_;
      result.title_ = title_;
      result.description_ = description_;
      result.posterUri_ = posterUri_;
      result.publishStatus_ = publishStatus_;
      result.auditStatus_ = auditStatus_;
      if (((bitField0_ & 0x00000001) != 0)) {
        tags_ = tags_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.tags_ = tags_;
      result.createTime_ = createTime_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BasicInfo) {
        return mergeFrom((BasicInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BasicInfo other) {
      if (other == BasicInfo.getDefaultInstance()) return this;
      if (!other.getSpaceName().isEmpty()) {
        spaceName_ = other.spaceName_;
        onChanged();
      }
      if (!other.getVid().isEmpty()) {
        vid_ = other.vid_;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getPosterUri().isEmpty()) {
        posterUri_ = other.posterUri_;
        onChanged();
      }
      if (!other.getPublishStatus().isEmpty()) {
        publishStatus_ = other.publishStatus_;
        onChanged();
      }
      if (other.getAuditStatus() != 0L) {
        setAuditStatus(other.getAuditStatus());
      }
      if (!other.tags_.isEmpty()) {
        if (tags_.isEmpty()) {
          tags_ = other.tags_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTagsIsMutable();
          tags_.addAll(other.tags_);
        }
        onChanged();
      }
      if (!other.getCreateTime().isEmpty()) {
        createTime_ = other.createTime_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      BasicInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (BasicInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object spaceName_ = "";
    /**
     * <pre>
     *空间名
     * </pre>
     *
     * <code>string SpaceName = 1;</code>
     * @return The spaceName.
     */
    public String getSpaceName() {
      Object ref = spaceName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        spaceName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *空间名
     * </pre>
     *
     * <code>string SpaceName = 1;</code>
     * @return The bytes for spaceName.
     */
    public com.google.protobuf.ByteString
        getSpaceNameBytes() {
      Object ref = spaceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        spaceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *空间名
     * </pre>
     *
     * <code>string SpaceName = 1;</code>
     * @param value The spaceName to set.
     * @return This builder for chaining.
     */
    public Builder setSpaceName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      spaceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *空间名
     * </pre>
     *
     * <code>string SpaceName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpaceName() {
      
      spaceName_ = getDefaultInstance().getSpaceName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *空间名
     * </pre>
     *
     * <code>string SpaceName = 1;</code>
     * @param value The bytes for spaceName to set.
     * @return This builder for chaining.
     */
    public Builder setSpaceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      spaceName_ = value;
      onChanged();
      return this;
    }

    private Object vid_ = "";
    /**
     * <pre>
     *视频ID
     * </pre>
     *
     * <code>string Vid = 2;</code>
     * @return The vid.
     */
    public String getVid() {
      Object ref = vid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        vid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *视频ID
     * </pre>
     *
     * <code>string Vid = 2;</code>
     * @return The bytes for vid.
     */
    public com.google.protobuf.ByteString
        getVidBytes() {
      Object ref = vid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        vid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *视频ID
     * </pre>
     *
     * <code>string Vid = 2;</code>
     * @param value The vid to set.
     * @return This builder for chaining.
     */
    public Builder setVid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频ID
     * </pre>
     *
     * <code>string Vid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVid() {
      
      vid_ = getDefaultInstance().getVid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频ID
     * </pre>
     *
     * <code>string Vid = 2;</code>
     * @param value The bytes for vid to set.
     * @return This builder for chaining.
     */
    public Builder setVidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vid_ = value;
      onChanged();
      return this;
    }

    private Object title_ = "";
    /**
     * <pre>
     *视频名称
     * </pre>
     *
     * <code>string Title = 3;</code>
     * @return The title.
     */
    public String getTitle() {
      Object ref = title_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *视频名称
     * </pre>
     *
     * <code>string Title = 3;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *视频名称
     * </pre>
     *
     * <code>string Title = 3;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频名称
     * </pre>
     *
     * <code>string Title = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频名称
     * </pre>
     *
     * <code>string Title = 3;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private Object description_ = "";
    /**
     * <pre>
     *视频描述
     * </pre>
     *
     * <code>string Description = 4;</code>
     * @return The description.
     */
    public String getDescription() {
      Object ref = description_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *视频描述
     * </pre>
     *
     * <code>string Description = 4;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *视频描述
     * </pre>
     *
     * <code>string Description = 4;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频描述
     * </pre>
     *
     * <code>string Description = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频描述
     * </pre>
     *
     * <code>string Description = 4;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private Object posterUri_ = "";
    /**
     * <pre>
     *封面图对象地址
     * </pre>
     *
     * <code>string PosterUri = 5;</code>
     * @return The posterUri.
     */
    public String getPosterUri() {
      Object ref = posterUri_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        posterUri_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *封面图对象地址
     * </pre>
     *
     * <code>string PosterUri = 5;</code>
     * @return The bytes for posterUri.
     */
    public com.google.protobuf.ByteString
        getPosterUriBytes() {
      Object ref = posterUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        posterUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *封面图对象地址
     * </pre>
     *
     * <code>string PosterUri = 5;</code>
     * @param value The posterUri to set.
     * @return This builder for chaining.
     */
    public Builder setPosterUri(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      posterUri_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *封面图对象地址
     * </pre>
     *
     * <code>string PosterUri = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosterUri() {
      
      posterUri_ = getDefaultInstance().getPosterUri();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *封面图对象地址
     * </pre>
     *
     * <code>string PosterUri = 5;</code>
     * @param value The bytes for posterUri to set.
     * @return This builder for chaining.
     */
    public Builder setPosterUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      posterUri_ = value;
      onChanged();
      return this;
    }

    private Object publishStatus_ = "";
    /**
     * <pre>
     *发布状态
     * </pre>
     *
     * <code>string PublishStatus = 6;</code>
     * @return The publishStatus.
     */
    public String getPublishStatus() {
      Object ref = publishStatus_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        publishStatus_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *发布状态
     * </pre>
     *
     * <code>string PublishStatus = 6;</code>
     * @return The bytes for publishStatus.
     */
    public com.google.protobuf.ByteString
        getPublishStatusBytes() {
      Object ref = publishStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        publishStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *发布状态
     * </pre>
     *
     * <code>string PublishStatus = 6;</code>
     * @param value The publishStatus to set.
     * @return This builder for chaining.
     */
    public Builder setPublishStatus(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      publishStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发布状态
     * </pre>
     *
     * <code>string PublishStatus = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublishStatus() {
      
      publishStatus_ = getDefaultInstance().getPublishStatus();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发布状态
     * </pre>
     *
     * <code>string PublishStatus = 6;</code>
     * @param value The bytes for publishStatus to set.
     * @return This builder for chaining.
     */
    public Builder setPublishStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      publishStatus_ = value;
      onChanged();
      return this;
    }

    private long auditStatus_ ;
    /**
     * <pre>
     *审核状态
     * </pre>
     *
     * <code>int64 AuditStatus = 7;</code>
     * @return The auditStatus.
     */
    @Override
    public long getAuditStatus() {
      return auditStatus_;
    }
    /**
     * <pre>
     *审核状态
     * </pre>
     *
     * <code>int64 AuditStatus = 7;</code>
     * @param value The auditStatus to set.
     * @return This builder for chaining.
     */
    public Builder setAuditStatus(long value) {
      
      auditStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *审核状态
     * </pre>
     *
     * <code>int64 AuditStatus = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuditStatus() {
      
      auditStatus_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTagsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     *标签列表
     * </pre>
     *
     * <code>repeated string Tags = 8;</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      return tags_.getUnmodifiableView();
    }
    /**
     * <pre>
     *标签列表
     * </pre>
     *
     * <code>repeated string Tags = 8;</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <pre>
     *标签列表
     * </pre>
     *
     * <code>repeated string Tags = 8;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <pre>
     *标签列表
     * </pre>
     *
     * <code>repeated string Tags = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }
    /**
     * <pre>
     *标签列表
     * </pre>
     *
     * <code>repeated string Tags = 8;</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     * @return This builder for chaining.
     */
    public Builder setTags(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
      tags_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标签列表
     * </pre>
     *
     * <code>repeated string Tags = 8;</code>
     * @param value The tags to add.
     * @return This builder for chaining.
     */
    public Builder addTags(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
      tags_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标签列表
     * </pre>
     *
     * <code>repeated string Tags = 8;</code>
     * @param values The tags to add.
     * @return This builder for chaining.
     */
    public Builder addAllTags(
        Iterable<String> values) {
      ensureTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tags_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标签列表
     * </pre>
     *
     * <code>repeated string Tags = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTags() {
      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标签列表
     * </pre>
     *
     * <code>repeated string Tags = 8;</code>
     * @param value The bytes of the tags to add.
     * @return This builder for chaining.
     */
    public Builder addTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTagsIsMutable();
      tags_.add(value);
      onChanged();
      return this;
    }

    private Object createTime_ = "";
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string CreateTime = 9;</code>
     * @return The createTime.
     */
    public String getCreateTime() {
      Object ref = createTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        createTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string CreateTime = 9;</code>
     * @return The bytes for createTime.
     */
    public com.google.protobuf.ByteString
        getCreateTimeBytes() {
      Object ref = createTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        createTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string CreateTime = 9;</code>
     * @param value The createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string CreateTime = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTime() {
      
      createTime_ = getDefaultInstance().getCreateTime();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string CreateTime = 9;</code>
     * @param value The bytes for createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createTime_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Vcloud.Models.Vod.BasicInfo)
  }

  // @@protoc_insertion_point(class_scope:Vcloud.Models.Vod.BasicInfo)
  private static final BasicInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BasicInfo();
  }

  public static BasicInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BasicInfo>
      PARSER = new com.google.protobuf.AbstractParser<BasicInfo>() {
    @Override
    public BasicInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BasicInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BasicInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BasicInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public BasicInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

