// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.bytedanceapi.model.common;

public interface ResponseMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Vcloud.Models.Base.ResponseMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 请求ID
   * </pre>
   *
   * <code>string RequestId = 1;</code>
   * @return The requestId.
   */
  String getRequestId();
  /**
   * <pre>
   * 请求ID
   * </pre>
   *
   * <code>string RequestId = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   * 请求接口
   * </pre>
   *
   * <code>string Action = 2;</code>
   * @return The action.
   */
  String getAction();
  /**
   * <pre>
   * 请求接口
   * </pre>
   *
   * <code>string Action = 2;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <pre>
   * 版本
   * </pre>
   *
   * <code>string Version = 3;</code>
   * @return The version.
   */
  String getVersion();
  /**
   * <pre>
   * 版本
   * </pre>
   *
   * <code>string Version = 3;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   * 服务
   * </pre>
   *
   * <code>string Service = 4;</code>
   * @return The service.
   */
  String getService();
  /**
   * <pre>
   * 服务
   * </pre>
   *
   * <code>string Service = 4;</code>
   * @return The bytes for service.
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <pre>
   * 区域
   * </pre>
   *
   * <code>string Region = 5;</code>
   * @return The region.
   */
  String getRegion();
  /**
   * <pre>
   * 区域
   * </pre>
   *
   * <code>string Region = 5;</code>
   * @return The bytes for region.
   */
  com.google.protobuf.ByteString
      getRegionBytes();

  /**
   * <pre>
   * 异常信息
   * </pre>
   *
   * <code>.Vcloud.Models.Base.ResponseError Error = 6;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <pre>
   * 异常信息
   * </pre>
   *
   * <code>.Vcloud.Models.Base.ResponseError Error = 6;</code>
   * @return The error.
   */
  ResponseError getError();
  /**
   * <pre>
   * 异常信息
   * </pre>
   *
   * <code>.Vcloud.Models.Base.ResponseError Error = 6;</code>
   */
  ResponseErrorOrBuilder getErrorOrBuilder();
}
