// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod_media.proto

package com.bytedanceapi.model.common;

/**
 * Protobuf type {@code Vcloud.Models.Vod.SourceInfo}
 */
public final class SourceInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Vcloud.Models.Vod.SourceInfo)
    SourceInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SourceInfo.newBuilder() to construct.
  private SourceInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SourceInfo() {
    fileId_ = "";
    md5_ = "";
    fileType_ = "";
    codec_ = "";
    format_ = "";
    storeUri_ = "";
    definition_ = "";
    createTime_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new SourceInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SourceInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            fileId_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            md5_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            fileType_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            codec_ = s;
            break;
          }
          case 40: {

            height_ = input.readInt64();
            break;
          }
          case 48: {

            width_ = input.readInt64();
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            format_ = s;
            break;
          }
          case 69: {

            duration_ = input.readFloat();
            break;
          }
          case 72: {

            size_ = input.readInt64();
            break;
          }
          case 82: {
            String s = input.readStringRequireUtf8();

            storeUri_ = s;
            break;
          }
          case 90: {
            String s = input.readStringRequireUtf8();

            definition_ = s;
            break;
          }
          case 96: {

            bitrate_ = input.readInt64();
            break;
          }
          case 109: {

            fps_ = input.readFloat();
            break;
          }
          case 114: {
            String s = input.readStringRequireUtf8();

            createTime_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return VodMedia.internal_static_Vcloud_Models_Vod_SourceInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return VodMedia.internal_static_Vcloud_Models_Vod_SourceInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SourceInfo.class, Builder.class);
  }

  public static final int FILEID_FIELD_NUMBER = 1;
  private volatile Object fileId_;
  /**
   * <pre>
   *文件ID
   * </pre>
   *
   * <code>string FileId = 1;</code>
   * @return The fileId.
   */
  @Override
  public String getFileId() {
    Object ref = fileId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      fileId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *文件ID
   * </pre>
   *
   * <code>string FileId = 1;</code>
   * @return The bytes for fileId.
   */
  @Override
  public com.google.protobuf.ByteString
      getFileIdBytes() {
    Object ref = fileId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      fileId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MD5_FIELD_NUMBER = 2;
  private volatile Object md5_;
  /**
   * <pre>
   * hash值
   * </pre>
   *
   * <code>string Md5 = 2;</code>
   * @return The md5.
   */
  @Override
  public String getMd5() {
    Object ref = md5_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      md5_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * hash值
   * </pre>
   *
   * <code>string Md5 = 2;</code>
   * @return The bytes for md5.
   */
  @Override
  public com.google.protobuf.ByteString
      getMd5Bytes() {
    Object ref = md5_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      md5_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILETYPE_FIELD_NUMBER = 3;
  private volatile Object fileType_;
  /**
   * <pre>
   *文件类型 video/audio
   * </pre>
   *
   * <code>string FileType = 3;</code>
   * @return The fileType.
   */
  @Override
  public String getFileType() {
    Object ref = fileType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      fileType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *文件类型 video/audio
   * </pre>
   *
   * <code>string FileType = 3;</code>
   * @return The bytes for fileType.
   */
  @Override
  public com.google.protobuf.ByteString
      getFileTypeBytes() {
    Object ref = fileType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      fileType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODEC_FIELD_NUMBER = 4;
  private volatile Object codec_;
  /**
   * <pre>
   *编码格式
   * </pre>
   *
   * <code>string Codec = 4;</code>
   * @return The codec.
   */
  @Override
  public String getCodec() {
    Object ref = codec_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      codec_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *编码格式
   * </pre>
   *
   * <code>string Codec = 4;</code>
   * @return The bytes for codec.
   */
  @Override
  public com.google.protobuf.ByteString
      getCodecBytes() {
    Object ref = codec_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      codec_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEIGHT_FIELD_NUMBER = 5;
  private long height_;
  /**
   * <pre>
   *视频高度
   * </pre>
   *
   * <code>int64 Height = 5;</code>
   * @return The height.
   */
  @Override
  public long getHeight() {
    return height_;
  }

  public static final int WIDTH_FIELD_NUMBER = 6;
  private long width_;
  /**
   * <pre>
   *视频宽度
   * </pre>
   *
   * <code>int64 Width = 6;</code>
   * @return The width.
   */
  @Override
  public long getWidth() {
    return width_;
  }

  public static final int FORMAT_FIELD_NUMBER = 7;
  private volatile Object format_;
  /**
   * <pre>
   *文件格式
   * </pre>
   *
   * <code>string Format = 7;</code>
   * @return The format.
   */
  @Override
  public String getFormat() {
    Object ref = format_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      format_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *文件格式
   * </pre>
   *
   * <code>string Format = 7;</code>
   * @return The bytes for format.
   */
  @Override
  public com.google.protobuf.ByteString
      getFormatBytes() {
    Object ref = format_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      format_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DURATION_FIELD_NUMBER = 8;
  private float duration_;
  /**
   * <pre>
   *时长
   * </pre>
   *
   * <code>float Duration = 8;</code>
   * @return The duration.
   */
  @Override
  public float getDuration() {
    return duration_;
  }

  public static final int SIZE_FIELD_NUMBER = 9;
  private long size_;
  /**
   * <pre>
   *文件大小
   * </pre>
   *
   * <code>int64 Size = 9;</code>
   * @return The size.
   */
  @Override
  public long getSize() {
    return size_;
  }

  public static final int STOREURI_FIELD_NUMBER = 10;
  private volatile Object storeUri_;
  /**
   * <pre>
   *对象地址
   * </pre>
   *
   * <code>string StoreUri = 10;</code>
   * @return The storeUri.
   */
  @Override
  public String getStoreUri() {
    Object ref = storeUri_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      storeUri_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *对象地址
   * </pre>
   *
   * <code>string StoreUri = 10;</code>
   * @return The bytes for storeUri.
   */
  @Override
  public com.google.protobuf.ByteString
      getStoreUriBytes() {
    Object ref = storeUri_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      storeUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEFINITION_FIELD_NUMBER = 11;
  private volatile Object definition_;
  /**
   * <pre>
   *视频分辨率
   * </pre>
   *
   * <code>string Definition = 11;</code>
   * @return The definition.
   */
  @Override
  public String getDefinition() {
    Object ref = definition_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      definition_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *视频分辨率
   * </pre>
   *
   * <code>string Definition = 11;</code>
   * @return The bytes for definition.
   */
  @Override
  public com.google.protobuf.ByteString
      getDefinitionBytes() {
    Object ref = definition_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      definition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BITRATE_FIELD_NUMBER = 12;
  private long bitrate_;
  /**
   * <pre>
   *码率(Kbps)
   * </pre>
   *
   * <code>int64 Bitrate = 12;</code>
   * @return The bitrate.
   */
  @Override
  public long getBitrate() {
    return bitrate_;
  }

  public static final int FPS_FIELD_NUMBER = 13;
  private float fps_;
  /**
   * <pre>
   *帧率
   * </pre>
   *
   * <code>float Fps = 13;</code>
   * @return The fps.
   */
  @Override
  public float getFps() {
    return fps_;
  }

  public static final int CREATETIME_FIELD_NUMBER = 14;
  private volatile Object createTime_;
  /**
   * <pre>
   *创建时间
   * </pre>
   *
   * <code>string CreateTime = 14;</code>
   * @return The createTime.
   */
  @Override
  public String getCreateTime() {
    Object ref = createTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      createTime_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *创建时间
   * </pre>
   *
   * <code>string CreateTime = 14;</code>
   * @return The bytes for createTime.
   */
  @Override
  public com.google.protobuf.ByteString
      getCreateTimeBytes() {
    Object ref = createTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      createTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFileIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileId_);
    }
    if (!getMd5Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, md5_);
    }
    if (!getFileTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fileType_);
    }
    if (!getCodecBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, codec_);
    }
    if (height_ != 0L) {
      output.writeInt64(5, height_);
    }
    if (width_ != 0L) {
      output.writeInt64(6, width_);
    }
    if (!getFormatBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, format_);
    }
    if (duration_ != 0F) {
      output.writeFloat(8, duration_);
    }
    if (size_ != 0L) {
      output.writeInt64(9, size_);
    }
    if (!getStoreUriBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, storeUri_);
    }
    if (!getDefinitionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, definition_);
    }
    if (bitrate_ != 0L) {
      output.writeInt64(12, bitrate_);
    }
    if (fps_ != 0F) {
      output.writeFloat(13, fps_);
    }
    if (!getCreateTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, createTime_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFileIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileId_);
    }
    if (!getMd5Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, md5_);
    }
    if (!getFileTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fileType_);
    }
    if (!getCodecBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, codec_);
    }
    if (height_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, height_);
    }
    if (width_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, width_);
    }
    if (!getFormatBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, format_);
    }
    if (duration_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(8, duration_);
    }
    if (size_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, size_);
    }
    if (!getStoreUriBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, storeUri_);
    }
    if (!getDefinitionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, definition_);
    }
    if (bitrate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, bitrate_);
    }
    if (fps_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(13, fps_);
    }
    if (!getCreateTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, createTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SourceInfo)) {
      return super.equals(obj);
    }
    SourceInfo other = (SourceInfo) obj;

    if (!getFileId()
        .equals(other.getFileId())) return false;
    if (!getMd5()
        .equals(other.getMd5())) return false;
    if (!getFileType()
        .equals(other.getFileType())) return false;
    if (!getCodec()
        .equals(other.getCodec())) return false;
    if (getHeight()
        != other.getHeight()) return false;
    if (getWidth()
        != other.getWidth()) return false;
    if (!getFormat()
        .equals(other.getFormat())) return false;
    if (Float.floatToIntBits(getDuration())
        != Float.floatToIntBits(
            other.getDuration())) return false;
    if (getSize()
        != other.getSize()) return false;
    if (!getStoreUri()
        .equals(other.getStoreUri())) return false;
    if (!getDefinition()
        .equals(other.getDefinition())) return false;
    if (getBitrate()
        != other.getBitrate()) return false;
    if (Float.floatToIntBits(getFps())
        != Float.floatToIntBits(
            other.getFps())) return false;
    if (!getCreateTime()
        .equals(other.getCreateTime())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILEID_FIELD_NUMBER;
    hash = (53 * hash) + getFileId().hashCode();
    hash = (37 * hash) + MD5_FIELD_NUMBER;
    hash = (53 * hash) + getMd5().hashCode();
    hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getFileType().hashCode();
    hash = (37 * hash) + CODEC_FIELD_NUMBER;
    hash = (53 * hash) + getCodec().hashCode();
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHeight());
    hash = (37 * hash) + WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWidth());
    hash = (37 * hash) + FORMAT_FIELD_NUMBER;
    hash = (53 * hash) + getFormat().hashCode();
    hash = (37 * hash) + DURATION_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getDuration());
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSize());
    hash = (37 * hash) + STOREURI_FIELD_NUMBER;
    hash = (53 * hash) + getStoreUri().hashCode();
    hash = (37 * hash) + DEFINITION_FIELD_NUMBER;
    hash = (53 * hash) + getDefinition().hashCode();
    hash = (37 * hash) + BITRATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBitrate());
    hash = (37 * hash) + FPS_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getFps());
    hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
    hash = (53 * hash) + getCreateTime().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SourceInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SourceInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SourceInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SourceInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SourceInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SourceInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SourceInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SourceInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SourceInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SourceInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SourceInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SourceInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SourceInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Vcloud.Models.Vod.SourceInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Vcloud.Models.Vod.SourceInfo)
      SourceInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VodMedia.internal_static_Vcloud_Models_Vod_SourceInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VodMedia.internal_static_Vcloud_Models_Vod_SourceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SourceInfo.class, Builder.class);
    }

    // Construct using com.bytedanceapi.model.common.SourceInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      fileId_ = "";

      md5_ = "";

      fileType_ = "";

      codec_ = "";

      height_ = 0L;

      width_ = 0L;

      format_ = "";

      duration_ = 0F;

      size_ = 0L;

      storeUri_ = "";

      definition_ = "";

      bitrate_ = 0L;

      fps_ = 0F;

      createTime_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return VodMedia.internal_static_Vcloud_Models_Vod_SourceInfo_descriptor;
    }

    @Override
    public SourceInfo getDefaultInstanceForType() {
      return SourceInfo.getDefaultInstance();
    }

    @Override
    public SourceInfo build() {
      SourceInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SourceInfo buildPartial() {
      SourceInfo result = new SourceInfo(this);
      result.fileId_ = fileId_;
      result.md5_ = md5_;
      result.fileType_ = fileType_;
      result.codec_ = codec_;
      result.height_ = height_;
      result.width_ = width_;
      result.format_ = format_;
      result.duration_ = duration_;
      result.size_ = size_;
      result.storeUri_ = storeUri_;
      result.definition_ = definition_;
      result.bitrate_ = bitrate_;
      result.fps_ = fps_;
      result.createTime_ = createTime_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SourceInfo) {
        return mergeFrom((SourceInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SourceInfo other) {
      if (other == SourceInfo.getDefaultInstance()) return this;
      if (!other.getFileId().isEmpty()) {
        fileId_ = other.fileId_;
        onChanged();
      }
      if (!other.getMd5().isEmpty()) {
        md5_ = other.md5_;
        onChanged();
      }
      if (!other.getFileType().isEmpty()) {
        fileType_ = other.fileType_;
        onChanged();
      }
      if (!other.getCodec().isEmpty()) {
        codec_ = other.codec_;
        onChanged();
      }
      if (other.getHeight() != 0L) {
        setHeight(other.getHeight());
      }
      if (other.getWidth() != 0L) {
        setWidth(other.getWidth());
      }
      if (!other.getFormat().isEmpty()) {
        format_ = other.format_;
        onChanged();
      }
      if (other.getDuration() != 0F) {
        setDuration(other.getDuration());
      }
      if (other.getSize() != 0L) {
        setSize(other.getSize());
      }
      if (!other.getStoreUri().isEmpty()) {
        storeUri_ = other.storeUri_;
        onChanged();
      }
      if (!other.getDefinition().isEmpty()) {
        definition_ = other.definition_;
        onChanged();
      }
      if (other.getBitrate() != 0L) {
        setBitrate(other.getBitrate());
      }
      if (other.getFps() != 0F) {
        setFps(other.getFps());
      }
      if (!other.getCreateTime().isEmpty()) {
        createTime_ = other.createTime_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SourceInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SourceInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object fileId_ = "";
    /**
     * <pre>
     *文件ID
     * </pre>
     *
     * <code>string FileId = 1;</code>
     * @return The fileId.
     */
    public String getFileId() {
      Object ref = fileId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *文件ID
     * </pre>
     *
     * <code>string FileId = 1;</code>
     * @return The bytes for fileId.
     */
    public com.google.protobuf.ByteString
        getFileIdBytes() {
      Object ref = fileId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *文件ID
     * </pre>
     *
     * <code>string FileId = 1;</code>
     * @param value The fileId to set.
     * @return This builder for chaining.
     */
    public Builder setFileId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件ID
     * </pre>
     *
     * <code>string FileId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileId() {
      
      fileId_ = getDefaultInstance().getFileId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件ID
     * </pre>
     *
     * <code>string FileId = 1;</code>
     * @param value The bytes for fileId to set.
     * @return This builder for chaining.
     */
    public Builder setFileIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileId_ = value;
      onChanged();
      return this;
    }

    private Object md5_ = "";
    /**
     * <pre>
     * hash值
     * </pre>
     *
     * <code>string Md5 = 2;</code>
     * @return The md5.
     */
    public String getMd5() {
      Object ref = md5_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        md5_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * hash值
     * </pre>
     *
     * <code>string Md5 = 2;</code>
     * @return The bytes for md5.
     */
    public com.google.protobuf.ByteString
        getMd5Bytes() {
      Object ref = md5_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        md5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * hash值
     * </pre>
     *
     * <code>string Md5 = 2;</code>
     * @param value The md5 to set.
     * @return This builder for chaining.
     */
    public Builder setMd5(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      md5_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * hash值
     * </pre>
     *
     * <code>string Md5 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMd5() {
      
      md5_ = getDefaultInstance().getMd5();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * hash值
     * </pre>
     *
     * <code>string Md5 = 2;</code>
     * @param value The bytes for md5 to set.
     * @return This builder for chaining.
     */
    public Builder setMd5Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      md5_ = value;
      onChanged();
      return this;
    }

    private Object fileType_ = "";
    /**
     * <pre>
     *文件类型 video/audio
     * </pre>
     *
     * <code>string FileType = 3;</code>
     * @return The fileType.
     */
    public String getFileType() {
      Object ref = fileType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *文件类型 video/audio
     * </pre>
     *
     * <code>string FileType = 3;</code>
     * @return The bytes for fileType.
     */
    public com.google.protobuf.ByteString
        getFileTypeBytes() {
      Object ref = fileType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *文件类型 video/audio
     * </pre>
     *
     * <code>string FileType = 3;</code>
     * @param value The fileType to set.
     * @return This builder for chaining.
     */
    public Builder setFileType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件类型 video/audio
     * </pre>
     *
     * <code>string FileType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileType() {
      
      fileType_ = getDefaultInstance().getFileType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件类型 video/audio
     * </pre>
     *
     * <code>string FileType = 3;</code>
     * @param value The bytes for fileType to set.
     * @return This builder for chaining.
     */
    public Builder setFileTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileType_ = value;
      onChanged();
      return this;
    }

    private Object codec_ = "";
    /**
     * <pre>
     *编码格式
     * </pre>
     *
     * <code>string Codec = 4;</code>
     * @return The codec.
     */
    public String getCodec() {
      Object ref = codec_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        codec_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *编码格式
     * </pre>
     *
     * <code>string Codec = 4;</code>
     * @return The bytes for codec.
     */
    public com.google.protobuf.ByteString
        getCodecBytes() {
      Object ref = codec_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        codec_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *编码格式
     * </pre>
     *
     * <code>string Codec = 4;</code>
     * @param value The codec to set.
     * @return This builder for chaining.
     */
    public Builder setCodec(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      codec_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *编码格式
     * </pre>
     *
     * <code>string Codec = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCodec() {
      
      codec_ = getDefaultInstance().getCodec();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *编码格式
     * </pre>
     *
     * <code>string Codec = 4;</code>
     * @param value The bytes for codec to set.
     * @return This builder for chaining.
     */
    public Builder setCodecBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      codec_ = value;
      onChanged();
      return this;
    }

    private long height_ ;
    /**
     * <pre>
     *视频高度
     * </pre>
     *
     * <code>int64 Height = 5;</code>
     * @return The height.
     */
    @Override
    public long getHeight() {
      return height_;
    }
    /**
     * <pre>
     *视频高度
     * </pre>
     *
     * <code>int64 Height = 5;</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(long value) {
      
      height_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频高度
     * </pre>
     *
     * <code>int64 Height = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      
      height_ = 0L;
      onChanged();
      return this;
    }

    private long width_ ;
    /**
     * <pre>
     *视频宽度
     * </pre>
     *
     * <code>int64 Width = 6;</code>
     * @return The width.
     */
    @Override
    public long getWidth() {
      return width_;
    }
    /**
     * <pre>
     *视频宽度
     * </pre>
     *
     * <code>int64 Width = 6;</code>
     * @param value The width to set.
     * @return This builder for chaining.
     */
    public Builder setWidth(long value) {
      
      width_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频宽度
     * </pre>
     *
     * <code>int64 Width = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearWidth() {
      
      width_ = 0L;
      onChanged();
      return this;
    }

    private Object format_ = "";
    /**
     * <pre>
     *文件格式
     * </pre>
     *
     * <code>string Format = 7;</code>
     * @return The format.
     */
    public String getFormat() {
      Object ref = format_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        format_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *文件格式
     * </pre>
     *
     * <code>string Format = 7;</code>
     * @return The bytes for format.
     */
    public com.google.protobuf.ByteString
        getFormatBytes() {
      Object ref = format_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        format_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *文件格式
     * </pre>
     *
     * <code>string Format = 7;</code>
     * @param value The format to set.
     * @return This builder for chaining.
     */
    public Builder setFormat(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      format_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件格式
     * </pre>
     *
     * <code>string Format = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFormat() {
      
      format_ = getDefaultInstance().getFormat();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件格式
     * </pre>
     *
     * <code>string Format = 7;</code>
     * @param value The bytes for format to set.
     * @return This builder for chaining.
     */
    public Builder setFormatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      format_ = value;
      onChanged();
      return this;
    }

    private float duration_ ;
    /**
     * <pre>
     *时长
     * </pre>
     *
     * <code>float Duration = 8;</code>
     * @return The duration.
     */
    @Override
    public float getDuration() {
      return duration_;
    }
    /**
     * <pre>
     *时长
     * </pre>
     *
     * <code>float Duration = 8;</code>
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(float value) {
      
      duration_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *时长
     * </pre>
     *
     * <code>float Duration = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      
      duration_ = 0F;
      onChanged();
      return this;
    }

    private long size_ ;
    /**
     * <pre>
     *文件大小
     * </pre>
     *
     * <code>int64 Size = 9;</code>
     * @return The size.
     */
    @Override
    public long getSize() {
      return size_;
    }
    /**
     * <pre>
     *文件大小
     * </pre>
     *
     * <code>int64 Size = 9;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(long value) {
      
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件大小
     * </pre>
     *
     * <code>int64 Size = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      
      size_ = 0L;
      onChanged();
      return this;
    }

    private Object storeUri_ = "";
    /**
     * <pre>
     *对象地址
     * </pre>
     *
     * <code>string StoreUri = 10;</code>
     * @return The storeUri.
     */
    public String getStoreUri() {
      Object ref = storeUri_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        storeUri_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *对象地址
     * </pre>
     *
     * <code>string StoreUri = 10;</code>
     * @return The bytes for storeUri.
     */
    public com.google.protobuf.ByteString
        getStoreUriBytes() {
      Object ref = storeUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        storeUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *对象地址
     * </pre>
     *
     * <code>string StoreUri = 10;</code>
     * @param value The storeUri to set.
     * @return This builder for chaining.
     */
    public Builder setStoreUri(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      storeUri_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *对象地址
     * </pre>
     *
     * <code>string StoreUri = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearStoreUri() {
      
      storeUri_ = getDefaultInstance().getStoreUri();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *对象地址
     * </pre>
     *
     * <code>string StoreUri = 10;</code>
     * @param value The bytes for storeUri to set.
     * @return This builder for chaining.
     */
    public Builder setStoreUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      storeUri_ = value;
      onChanged();
      return this;
    }

    private Object definition_ = "";
    /**
     * <pre>
     *视频分辨率
     * </pre>
     *
     * <code>string Definition = 11;</code>
     * @return The definition.
     */
    public String getDefinition() {
      Object ref = definition_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        definition_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *视频分辨率
     * </pre>
     *
     * <code>string Definition = 11;</code>
     * @return The bytes for definition.
     */
    public com.google.protobuf.ByteString
        getDefinitionBytes() {
      Object ref = definition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        definition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *视频分辨率
     * </pre>
     *
     * <code>string Definition = 11;</code>
     * @param value The definition to set.
     * @return This builder for chaining.
     */
    public Builder setDefinition(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      definition_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频分辨率
     * </pre>
     *
     * <code>string Definition = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefinition() {
      
      definition_ = getDefaultInstance().getDefinition();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频分辨率
     * </pre>
     *
     * <code>string Definition = 11;</code>
     * @param value The bytes for definition to set.
     * @return This builder for chaining.
     */
    public Builder setDefinitionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      definition_ = value;
      onChanged();
      return this;
    }

    private long bitrate_ ;
    /**
     * <pre>
     *码率(Kbps)
     * </pre>
     *
     * <code>int64 Bitrate = 12;</code>
     * @return The bitrate.
     */
    @Override
    public long getBitrate() {
      return bitrate_;
    }
    /**
     * <pre>
     *码率(Kbps)
     * </pre>
     *
     * <code>int64 Bitrate = 12;</code>
     * @param value The bitrate to set.
     * @return This builder for chaining.
     */
    public Builder setBitrate(long value) {
      
      bitrate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *码率(Kbps)
     * </pre>
     *
     * <code>int64 Bitrate = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearBitrate() {
      
      bitrate_ = 0L;
      onChanged();
      return this;
    }

    private float fps_ ;
    /**
     * <pre>
     *帧率
     * </pre>
     *
     * <code>float Fps = 13;</code>
     * @return The fps.
     */
    @Override
    public float getFps() {
      return fps_;
    }
    /**
     * <pre>
     *帧率
     * </pre>
     *
     * <code>float Fps = 13;</code>
     * @param value The fps to set.
     * @return This builder for chaining.
     */
    public Builder setFps(float value) {
      
      fps_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *帧率
     * </pre>
     *
     * <code>float Fps = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearFps() {
      
      fps_ = 0F;
      onChanged();
      return this;
    }

    private Object createTime_ = "";
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string CreateTime = 14;</code>
     * @return The createTime.
     */
    public String getCreateTime() {
      Object ref = createTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        createTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string CreateTime = 14;</code>
     * @return The bytes for createTime.
     */
    public com.google.protobuf.ByteString
        getCreateTimeBytes() {
      Object ref = createTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        createTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string CreateTime = 14;</code>
     * @param value The createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string CreateTime = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTime() {
      
      createTime_ = getDefaultInstance().getCreateTime();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string CreateTime = 14;</code>
     * @param value The bytes for createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createTime_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Vcloud.Models.Vod.SourceInfo)
  }

  // @@protoc_insertion_point(class_scope:Vcloud.Models.Vod.SourceInfo)
  private static final SourceInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SourceInfo();
  }

  public static SourceInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SourceInfo>
      PARSER = new com.google.protobuf.AbstractParser<SourceInfo>() {
    @Override
    public SourceInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SourceInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SourceInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SourceInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public SourceInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

