// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod_media.proto

package com.bytedanceapi.model.common;

public interface VideoInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Vcloud.Models.Vod.VideoInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *视频基础信息
   * </pre>
   *
   * <code>.Vcloud.Models.Vod.BasicInfo BasicInfo = 1;</code>
   * @return Whether the basicInfo field is set.
   */
  boolean hasBasicInfo();
  /**
   * <pre>
   *视频基础信息
   * </pre>
   *
   * <code>.Vcloud.Models.Vod.BasicInfo BasicInfo = 1;</code>
   * @return The basicInfo.
   */
  BasicInfo getBasicInfo();
  /**
   * <pre>
   *视频基础信息
   * </pre>
   *
   * <code>.Vcloud.Models.Vod.BasicInfo BasicInfo = 1;</code>
   */
  BasicInfoOrBuilder getBasicInfoOrBuilder();

  /**
   * <pre>
   *原视频信息
   * </pre>
   *
   * <code>.Vcloud.Models.Vod.SourceInfo SourceInfo = 2;</code>
   * @return Whether the sourceInfo field is set.
   */
  boolean hasSourceInfo();
  /**
   * <pre>
   *原视频信息
   * </pre>
   *
   * <code>.Vcloud.Models.Vod.SourceInfo SourceInfo = 2;</code>
   * @return The sourceInfo.
   */
  SourceInfo getSourceInfo();
  /**
   * <pre>
   *原视频信息
   * </pre>
   *
   * <code>.Vcloud.Models.Vod.SourceInfo SourceInfo = 2;</code>
   */
  SourceInfoOrBuilder getSourceInfoOrBuilder();

  /**
   * <pre>
   *转码视频信息列表
   * </pre>
   *
   * <code>repeated .Vcloud.Models.Vod.TranscodeInfo TranscodeInfos = 3;</code>
   */
  java.util.List<TranscodeInfo>
      getTranscodeInfosList();
  /**
   * <pre>
   *转码视频信息列表
   * </pre>
   *
   * <code>repeated .Vcloud.Models.Vod.TranscodeInfo TranscodeInfos = 3;</code>
   */
  TranscodeInfo getTranscodeInfos(int index);
  /**
   * <pre>
   *转码视频信息列表
   * </pre>
   *
   * <code>repeated .Vcloud.Models.Vod.TranscodeInfo TranscodeInfos = 3;</code>
   */
  int getTranscodeInfosCount();
  /**
   * <pre>
   *转码视频信息列表
   * </pre>
   *
   * <code>repeated .Vcloud.Models.Vod.TranscodeInfo TranscodeInfos = 3;</code>
   */
  java.util.List<? extends TranscodeInfoOrBuilder>
      getTranscodeInfosOrBuilderList();
  /**
   * <pre>
   *转码视频信息列表
   * </pre>
   *
   * <code>repeated .Vcloud.Models.Vod.TranscodeInfo TranscodeInfos = 3;</code>
   */
  TranscodeInfoOrBuilder getTranscodeInfosOrBuilder(
      int index);
}
