// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod_media.proto

package com.bytedanceapi.model.common;

/**
 * Protobuf type {@code Vcloud.Models.Vod.VideoStreamMeta}
 */
public final class VideoStreamMeta extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Vcloud.Models.Vod.VideoStreamMeta)
    VideoStreamMetaOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VideoStreamMeta.newBuilder() to construct.
  private VideoStreamMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VideoStreamMeta() {
    codec_ = "";
    definition_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new VideoStreamMeta();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VideoStreamMeta(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            codec_ = s;
            break;
          }
          case 16: {

            height_ = input.readInt64();
            break;
          }
          case 24: {

            width_ = input.readInt64();
            break;
          }
          case 37: {

            duration_ = input.readFloat();
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            definition_ = s;
            break;
          }
          case 48: {

            bitrate_ = input.readInt64();
            break;
          }
          case 61: {

            fps_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return VodMedia.internal_static_Vcloud_Models_Vod_VideoStreamMeta_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return VodMedia.internal_static_Vcloud_Models_Vod_VideoStreamMeta_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            VideoStreamMeta.class, Builder.class);
  }

  public static final int CODEC_FIELD_NUMBER = 1;
  private volatile Object codec_;
  /**
   * <pre>
   *视频编码格式
   * </pre>
   *
   * <code>string Codec = 1;</code>
   * @return The codec.
   */
  @Override
  public String getCodec() {
    Object ref = codec_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      codec_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *视频编码格式
   * </pre>
   *
   * <code>string Codec = 1;</code>
   * @return The bytes for codec.
   */
  @Override
  public com.google.protobuf.ByteString
      getCodecBytes() {
    Object ref = codec_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      codec_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEIGHT_FIELD_NUMBER = 2;
  private long height_;
  /**
   * <pre>
   *视频高度
   * </pre>
   *
   * <code>int64 Height = 2;</code>
   * @return The height.
   */
  @Override
  public long getHeight() {
    return height_;
  }

  public static final int WIDTH_FIELD_NUMBER = 3;
  private long width_;
  /**
   * <pre>
   *视频宽度
   * </pre>
   *
   * <code>int64 Width = 3;</code>
   * @return The width.
   */
  @Override
  public long getWidth() {
    return width_;
  }

  public static final int DURATION_FIELD_NUMBER = 4;
  private float duration_;
  /**
   * <pre>
   *视频时长
   * </pre>
   *
   * <code>float Duration = 4;</code>
   * @return The duration.
   */
  @Override
  public float getDuration() {
    return duration_;
  }

  public static final int DEFINITION_FIELD_NUMBER = 5;
  private volatile Object definition_;
  /**
   * <pre>
   *视频清晰度
   * </pre>
   *
   * <code>string Definition = 5;</code>
   * @return The definition.
   */
  @Override
  public String getDefinition() {
    Object ref = definition_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      definition_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *视频清晰度
   * </pre>
   *
   * <code>string Definition = 5;</code>
   * @return The bytes for definition.
   */
  @Override
  public com.google.protobuf.ByteString
      getDefinitionBytes() {
    Object ref = definition_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      definition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BITRATE_FIELD_NUMBER = 6;
  private long bitrate_;
  /**
   * <pre>
   *视频码率(Kbps)
   * </pre>
   *
   * <code>int64 Bitrate = 6;</code>
   * @return The bitrate.
   */
  @Override
  public long getBitrate() {
    return bitrate_;
  }

  public static final int FPS_FIELD_NUMBER = 7;
  private float fps_;
  /**
   * <pre>
   *帧率
   * </pre>
   *
   * <code>float Fps = 7;</code>
   * @return The fps.
   */
  @Override
  public float getFps() {
    return fps_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCodecBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, codec_);
    }
    if (height_ != 0L) {
      output.writeInt64(2, height_);
    }
    if (width_ != 0L) {
      output.writeInt64(3, width_);
    }
    if (duration_ != 0F) {
      output.writeFloat(4, duration_);
    }
    if (!getDefinitionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, definition_);
    }
    if (bitrate_ != 0L) {
      output.writeInt64(6, bitrate_);
    }
    if (fps_ != 0F) {
      output.writeFloat(7, fps_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCodecBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, codec_);
    }
    if (height_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, height_);
    }
    if (width_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, width_);
    }
    if (duration_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, duration_);
    }
    if (!getDefinitionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, definition_);
    }
    if (bitrate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, bitrate_);
    }
    if (fps_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(7, fps_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof VideoStreamMeta)) {
      return super.equals(obj);
    }
    VideoStreamMeta other = (VideoStreamMeta) obj;

    if (!getCodec()
        .equals(other.getCodec())) return false;
    if (getHeight()
        != other.getHeight()) return false;
    if (getWidth()
        != other.getWidth()) return false;
    if (Float.floatToIntBits(getDuration())
        != Float.floatToIntBits(
            other.getDuration())) return false;
    if (!getDefinition()
        .equals(other.getDefinition())) return false;
    if (getBitrate()
        != other.getBitrate()) return false;
    if (Float.floatToIntBits(getFps())
        != Float.floatToIntBits(
            other.getFps())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODEC_FIELD_NUMBER;
    hash = (53 * hash) + getCodec().hashCode();
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHeight());
    hash = (37 * hash) + WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWidth());
    hash = (37 * hash) + DURATION_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getDuration());
    hash = (37 * hash) + DEFINITION_FIELD_NUMBER;
    hash = (53 * hash) + getDefinition().hashCode();
    hash = (37 * hash) + BITRATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBitrate());
    hash = (37 * hash) + FPS_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getFps());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static VideoStreamMeta parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VideoStreamMeta parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VideoStreamMeta parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VideoStreamMeta parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VideoStreamMeta parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VideoStreamMeta parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VideoStreamMeta parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VideoStreamMeta parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static VideoStreamMeta parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static VideoStreamMeta parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static VideoStreamMeta parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VideoStreamMeta parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(VideoStreamMeta prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Vcloud.Models.Vod.VideoStreamMeta}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Vcloud.Models.Vod.VideoStreamMeta)
      VideoStreamMetaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VodMedia.internal_static_Vcloud_Models_Vod_VideoStreamMeta_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VodMedia.internal_static_Vcloud_Models_Vod_VideoStreamMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VideoStreamMeta.class, Builder.class);
    }

    // Construct using com.bytedanceapi.model.common.VideoStreamMeta.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      codec_ = "";

      height_ = 0L;

      width_ = 0L;

      duration_ = 0F;

      definition_ = "";

      bitrate_ = 0L;

      fps_ = 0F;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return VodMedia.internal_static_Vcloud_Models_Vod_VideoStreamMeta_descriptor;
    }

    @Override
    public VideoStreamMeta getDefaultInstanceForType() {
      return VideoStreamMeta.getDefaultInstance();
    }

    @Override
    public VideoStreamMeta build() {
      VideoStreamMeta result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public VideoStreamMeta buildPartial() {
      VideoStreamMeta result = new VideoStreamMeta(this);
      result.codec_ = codec_;
      result.height_ = height_;
      result.width_ = width_;
      result.duration_ = duration_;
      result.definition_ = definition_;
      result.bitrate_ = bitrate_;
      result.fps_ = fps_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof VideoStreamMeta) {
        return mergeFrom((VideoStreamMeta)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(VideoStreamMeta other) {
      if (other == VideoStreamMeta.getDefaultInstance()) return this;
      if (!other.getCodec().isEmpty()) {
        codec_ = other.codec_;
        onChanged();
      }
      if (other.getHeight() != 0L) {
        setHeight(other.getHeight());
      }
      if (other.getWidth() != 0L) {
        setWidth(other.getWidth());
      }
      if (other.getDuration() != 0F) {
        setDuration(other.getDuration());
      }
      if (!other.getDefinition().isEmpty()) {
        definition_ = other.definition_;
        onChanged();
      }
      if (other.getBitrate() != 0L) {
        setBitrate(other.getBitrate());
      }
      if (other.getFps() != 0F) {
        setFps(other.getFps());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      VideoStreamMeta parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (VideoStreamMeta) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object codec_ = "";
    /**
     * <pre>
     *视频编码格式
     * </pre>
     *
     * <code>string Codec = 1;</code>
     * @return The codec.
     */
    public String getCodec() {
      Object ref = codec_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        codec_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *视频编码格式
     * </pre>
     *
     * <code>string Codec = 1;</code>
     * @return The bytes for codec.
     */
    public com.google.protobuf.ByteString
        getCodecBytes() {
      Object ref = codec_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        codec_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *视频编码格式
     * </pre>
     *
     * <code>string Codec = 1;</code>
     * @param value The codec to set.
     * @return This builder for chaining.
     */
    public Builder setCodec(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      codec_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频编码格式
     * </pre>
     *
     * <code>string Codec = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCodec() {
      
      codec_ = getDefaultInstance().getCodec();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频编码格式
     * </pre>
     *
     * <code>string Codec = 1;</code>
     * @param value The bytes for codec to set.
     * @return This builder for chaining.
     */
    public Builder setCodecBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      codec_ = value;
      onChanged();
      return this;
    }

    private long height_ ;
    /**
     * <pre>
     *视频高度
     * </pre>
     *
     * <code>int64 Height = 2;</code>
     * @return The height.
     */
    @Override
    public long getHeight() {
      return height_;
    }
    /**
     * <pre>
     *视频高度
     * </pre>
     *
     * <code>int64 Height = 2;</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(long value) {
      
      height_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频高度
     * </pre>
     *
     * <code>int64 Height = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      
      height_ = 0L;
      onChanged();
      return this;
    }

    private long width_ ;
    /**
     * <pre>
     *视频宽度
     * </pre>
     *
     * <code>int64 Width = 3;</code>
     * @return The width.
     */
    @Override
    public long getWidth() {
      return width_;
    }
    /**
     * <pre>
     *视频宽度
     * </pre>
     *
     * <code>int64 Width = 3;</code>
     * @param value The width to set.
     * @return This builder for chaining.
     */
    public Builder setWidth(long value) {
      
      width_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频宽度
     * </pre>
     *
     * <code>int64 Width = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWidth() {
      
      width_ = 0L;
      onChanged();
      return this;
    }

    private float duration_ ;
    /**
     * <pre>
     *视频时长
     * </pre>
     *
     * <code>float Duration = 4;</code>
     * @return The duration.
     */
    @Override
    public float getDuration() {
      return duration_;
    }
    /**
     * <pre>
     *视频时长
     * </pre>
     *
     * <code>float Duration = 4;</code>
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(float value) {
      
      duration_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频时长
     * </pre>
     *
     * <code>float Duration = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      
      duration_ = 0F;
      onChanged();
      return this;
    }

    private Object definition_ = "";
    /**
     * <pre>
     *视频清晰度
     * </pre>
     *
     * <code>string Definition = 5;</code>
     * @return The definition.
     */
    public String getDefinition() {
      Object ref = definition_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        definition_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *视频清晰度
     * </pre>
     *
     * <code>string Definition = 5;</code>
     * @return The bytes for definition.
     */
    public com.google.protobuf.ByteString
        getDefinitionBytes() {
      Object ref = definition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        definition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *视频清晰度
     * </pre>
     *
     * <code>string Definition = 5;</code>
     * @param value The definition to set.
     * @return This builder for chaining.
     */
    public Builder setDefinition(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      definition_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频清晰度
     * </pre>
     *
     * <code>string Definition = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefinition() {
      
      definition_ = getDefaultInstance().getDefinition();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频清晰度
     * </pre>
     *
     * <code>string Definition = 5;</code>
     * @param value The bytes for definition to set.
     * @return This builder for chaining.
     */
    public Builder setDefinitionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      definition_ = value;
      onChanged();
      return this;
    }

    private long bitrate_ ;
    /**
     * <pre>
     *视频码率(Kbps)
     * </pre>
     *
     * <code>int64 Bitrate = 6;</code>
     * @return The bitrate.
     */
    @Override
    public long getBitrate() {
      return bitrate_;
    }
    /**
     * <pre>
     *视频码率(Kbps)
     * </pre>
     *
     * <code>int64 Bitrate = 6;</code>
     * @param value The bitrate to set.
     * @return This builder for chaining.
     */
    public Builder setBitrate(long value) {
      
      bitrate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频码率(Kbps)
     * </pre>
     *
     * <code>int64 Bitrate = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBitrate() {
      
      bitrate_ = 0L;
      onChanged();
      return this;
    }

    private float fps_ ;
    /**
     * <pre>
     *帧率
     * </pre>
     *
     * <code>float Fps = 7;</code>
     * @return The fps.
     */
    @Override
    public float getFps() {
      return fps_;
    }
    /**
     * <pre>
     *帧率
     * </pre>
     *
     * <code>float Fps = 7;</code>
     * @param value The fps to set.
     * @return This builder for chaining.
     */
    public Builder setFps(float value) {
      
      fps_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *帧率
     * </pre>
     *
     * <code>float Fps = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFps() {
      
      fps_ = 0F;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Vcloud.Models.Vod.VideoStreamMeta)
  }

  // @@protoc_insertion_point(class_scope:Vcloud.Models.Vod.VideoStreamMeta)
  private static final VideoStreamMeta DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new VideoStreamMeta();
  }

  public static VideoStreamMeta getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VideoStreamMeta>
      PARSER = new com.google.protobuf.AbstractParser<VideoStreamMeta>() {
    @Override
    public VideoStreamMeta parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VideoStreamMeta(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VideoStreamMeta> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<VideoStreamMeta> getParserForType() {
    return PARSER;
  }

  @Override
  public VideoStreamMeta getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

