// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod_play.proto

package com.bytedanceapi.model.common;

public interface VodGetOriginalPlayInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Vcloud.Models.Vod.VodGetOriginalPlayInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *视频ID
   * </pre>
   *
   * <code>string Vid = 1;</code>
   * @return The vid.
   */
  java.lang.String getVid();
  /**
   * <pre>
   *视频ID
   * </pre>
   *
   * <code>string Vid = 1;</code>
   * @return The bytes for vid.
   */
  com.google.protobuf.ByteString
      getVidBytes();

  /**
   * <pre>
   *播放地址是否base64编码,默认否，0-否，1-是
   * </pre>
   *
   * <code>int64 Base64 = 2;</code>
   * @return The base64.
   */
  long getBase64();

  /**
   * <pre>
   *返回https播放地址,默认否, 0-否，1-是
   * </pre>
   *
   * <code>int64 Ssl = 3;</code>
   * @return The ssl.
   */
  long getSsl();
}
