// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod_play.proto

package com.bytedanceapi.model.common;

/**
 * Protobuf type {@code Vcloud.Models.Vod.VodGetOriginalPlayInfoRequest}
 */
public final class VodGetOriginalPlayInfoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Vcloud.Models.Vod.VodGetOriginalPlayInfoRequest)
    VodGetOriginalPlayInfoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VodGetOriginalPlayInfoRequest.newBuilder() to construct.
  private VodGetOriginalPlayInfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VodGetOriginalPlayInfoRequest() {
    vid_ = "";
    base64_ = "";
    ssl_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new VodGetOriginalPlayInfoRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VodGetOriginalPlayInfoRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            vid_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            base64_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            ssl_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return VodPlay.internal_static_Vcloud_Models_Vod_VodGetOriginalPlayInfoRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return VodPlay.internal_static_Vcloud_Models_Vod_VodGetOriginalPlayInfoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            VodGetOriginalPlayInfoRequest.class, Builder.class);
  }

  public static final int VID_FIELD_NUMBER = 1;
  private volatile Object vid_;
  /**
   * <pre>
   *视频ID
   * </pre>
   *
   * <code>string Vid = 1;</code>
   * @return The vid.
   */
  @Override
  public String getVid() {
    Object ref = vid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      vid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *视频ID
   * </pre>
   *
   * <code>string Vid = 1;</code>
   * @return The bytes for vid.
   */
  @Override
  public com.google.protobuf.ByteString
      getVidBytes() {
    Object ref = vid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      vid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BASE64_FIELD_NUMBER = 2;
  private volatile Object base64_;
  /**
   * <pre>
   *播放地址是否base64编码,默认否，0-否，1-是
   * </pre>
   *
   * <code>string Base64 = 2;</code>
   * @return The base64.
   */
  @Override
  public String getBase64() {
    Object ref = base64_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      base64_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *播放地址是否base64编码,默认否，0-否，1-是
   * </pre>
   *
   * <code>string Base64 = 2;</code>
   * @return The bytes for base64.
   */
  @Override
  public com.google.protobuf.ByteString
      getBase64Bytes() {
    Object ref = base64_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      base64_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SSL_FIELD_NUMBER = 3;
  private volatile Object ssl_;
  /**
   * <pre>
   *返回https播放地址,默认否, 0-否，1-是
   * </pre>
   *
   * <code>string Ssl = 3;</code>
   * @return The ssl.
   */
  @Override
  public String getSsl() {
    Object ref = ssl_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ssl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *返回https播放地址,默认否, 0-否，1-是
   * </pre>
   *
   * <code>string Ssl = 3;</code>
   * @return The bytes for ssl.
   */
  @Override
  public com.google.protobuf.ByteString
      getSslBytes() {
    Object ref = ssl_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ssl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getVidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vid_);
    }
    if (!getBase64Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, base64_);
    }
    if (!getSslBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ssl_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getVidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vid_);
    }
    if (!getBase64Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, base64_);
    }
    if (!getSslBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ssl_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof VodGetOriginalPlayInfoRequest)) {
      return super.equals(obj);
    }
    VodGetOriginalPlayInfoRequest other = (VodGetOriginalPlayInfoRequest) obj;

    if (!getVid()
        .equals(other.getVid())) return false;
    if (!getBase64()
        .equals(other.getBase64())) return false;
    if (!getSsl()
        .equals(other.getSsl())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VID_FIELD_NUMBER;
    hash = (53 * hash) + getVid().hashCode();
    hash = (37 * hash) + BASE64_FIELD_NUMBER;
    hash = (53 * hash) + getBase64().hashCode();
    hash = (37 * hash) + SSL_FIELD_NUMBER;
    hash = (53 * hash) + getSsl().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static VodGetOriginalPlayInfoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VodGetOriginalPlayInfoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VodGetOriginalPlayInfoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VodGetOriginalPlayInfoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VodGetOriginalPlayInfoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VodGetOriginalPlayInfoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VodGetOriginalPlayInfoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VodGetOriginalPlayInfoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static VodGetOriginalPlayInfoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static VodGetOriginalPlayInfoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static VodGetOriginalPlayInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VodGetOriginalPlayInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(VodGetOriginalPlayInfoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Vcloud.Models.Vod.VodGetOriginalPlayInfoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Vcloud.Models.Vod.VodGetOriginalPlayInfoRequest)
      VodGetOriginalPlayInfoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VodPlay.internal_static_Vcloud_Models_Vod_VodGetOriginalPlayInfoRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VodPlay.internal_static_Vcloud_Models_Vod_VodGetOriginalPlayInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VodGetOriginalPlayInfoRequest.class, Builder.class);
    }

    // Construct using com.bytedanceapi.model.common.VodGetOriginalPlayInfoRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      vid_ = "";

      base64_ = "";

      ssl_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return VodPlay.internal_static_Vcloud_Models_Vod_VodGetOriginalPlayInfoRequest_descriptor;
    }

    @Override
    public VodGetOriginalPlayInfoRequest getDefaultInstanceForType() {
      return VodGetOriginalPlayInfoRequest.getDefaultInstance();
    }

    @Override
    public VodGetOriginalPlayInfoRequest build() {
      VodGetOriginalPlayInfoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public VodGetOriginalPlayInfoRequest buildPartial() {
      VodGetOriginalPlayInfoRequest result = new VodGetOriginalPlayInfoRequest(this);
      result.vid_ = vid_;
      result.base64_ = base64_;
      result.ssl_ = ssl_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof VodGetOriginalPlayInfoRequest) {
        return mergeFrom((VodGetOriginalPlayInfoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(VodGetOriginalPlayInfoRequest other) {
      if (other == VodGetOriginalPlayInfoRequest.getDefaultInstance()) return this;
      if (!other.getVid().isEmpty()) {
        vid_ = other.vid_;
        onChanged();
      }
      if (!other.getBase64().isEmpty()) {
        base64_ = other.base64_;
        onChanged();
      }
      if (!other.getSsl().isEmpty()) {
        ssl_ = other.ssl_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      VodGetOriginalPlayInfoRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (VodGetOriginalPlayInfoRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object vid_ = "";
    /**
     * <pre>
     *视频ID
     * </pre>
     *
     * <code>string Vid = 1;</code>
     * @return The vid.
     */
    public String getVid() {
      Object ref = vid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        vid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *视频ID
     * </pre>
     *
     * <code>string Vid = 1;</code>
     * @return The bytes for vid.
     */
    public com.google.protobuf.ByteString
        getVidBytes() {
      Object ref = vid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        vid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *视频ID
     * </pre>
     *
     * <code>string Vid = 1;</code>
     * @param value The vid to set.
     * @return This builder for chaining.
     */
    public Builder setVid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频ID
     * </pre>
     *
     * <code>string Vid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVid() {
      
      vid_ = getDefaultInstance().getVid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *视频ID
     * </pre>
     *
     * <code>string Vid = 1;</code>
     * @param value The bytes for vid to set.
     * @return This builder for chaining.
     */
    public Builder setVidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vid_ = value;
      onChanged();
      return this;
    }

    private Object base64_ = "";
    /**
     * <pre>
     *播放地址是否base64编码,默认否，0-否，1-是
     * </pre>
     *
     * <code>string Base64 = 2;</code>
     * @return The base64.
     */
    public String getBase64() {
      Object ref = base64_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        base64_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *播放地址是否base64编码,默认否，0-否，1-是
     * </pre>
     *
     * <code>string Base64 = 2;</code>
     * @return The bytes for base64.
     */
    public com.google.protobuf.ByteString
        getBase64Bytes() {
      Object ref = base64_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        base64_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *播放地址是否base64编码,默认否，0-否，1-是
     * </pre>
     *
     * <code>string Base64 = 2;</code>
     * @param value The base64 to set.
     * @return This builder for chaining.
     */
    public Builder setBase64(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      base64_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *播放地址是否base64编码,默认否，0-否，1-是
     * </pre>
     *
     * <code>string Base64 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBase64() {
      
      base64_ = getDefaultInstance().getBase64();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *播放地址是否base64编码,默认否，0-否，1-是
     * </pre>
     *
     * <code>string Base64 = 2;</code>
     * @param value The bytes for base64 to set.
     * @return This builder for chaining.
     */
    public Builder setBase64Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      base64_ = value;
      onChanged();
      return this;
    }

    private Object ssl_ = "";
    /**
     * <pre>
     *返回https播放地址,默认否, 0-否，1-是
     * </pre>
     *
     * <code>string Ssl = 3;</code>
     * @return The ssl.
     */
    public String getSsl() {
      Object ref = ssl_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ssl_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *返回https播放地址,默认否, 0-否，1-是
     * </pre>
     *
     * <code>string Ssl = 3;</code>
     * @return The bytes for ssl.
     */
    public com.google.protobuf.ByteString
        getSslBytes() {
      Object ref = ssl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ssl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *返回https播放地址,默认否, 0-否，1-是
     * </pre>
     *
     * <code>string Ssl = 3;</code>
     * @param value The ssl to set.
     * @return This builder for chaining.
     */
    public Builder setSsl(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ssl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *返回https播放地址,默认否, 0-否，1-是
     * </pre>
     *
     * <code>string Ssl = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSsl() {
      
      ssl_ = getDefaultInstance().getSsl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *返回https播放地址,默认否, 0-否，1-是
     * </pre>
     *
     * <code>string Ssl = 3;</code>
     * @param value The bytes for ssl to set.
     * @return This builder for chaining.
     */
    public Builder setSslBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ssl_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Vcloud.Models.Vod.VodGetOriginalPlayInfoRequest)
  }

  // @@protoc_insertion_point(class_scope:Vcloud.Models.Vod.VodGetOriginalPlayInfoRequest)
  private static final VodGetOriginalPlayInfoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new VodGetOriginalPlayInfoRequest();
  }

  public static VodGetOriginalPlayInfoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VodGetOriginalPlayInfoRequest>
      PARSER = new com.google.protobuf.AbstractParser<VodGetOriginalPlayInfoRequest>() {
    @Override
    public VodGetOriginalPlayInfoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VodGetOriginalPlayInfoRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VodGetOriginalPlayInfoRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<VodGetOriginalPlayInfoRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public VodGetOriginalPlayInfoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

