
// Code generated by protoc-gen-volcengine-sdk
// source: vod/service/service_vod.proto
// DO NOT EDIT!

package com.bytedanceapi.service.vod;

/**
 * The interface Vod service.
 */
public interface IVodService extends com.bytedanceapi.service.IBaseService {

	/**
     * Gets play auth token.
     *
     * @param params the params
     * @return the play auth token
     * @throws Exception the exception
     */
    String getPlayAuthToken(java.util.Map<String, String> params) throws Exception;

	/**
     * Gets upload auth token.
     *
     * @param params the params
     * @return the upload auth token
     * @throws Exception the exception
     */
    String getUploadAuthToken(java.util.Map<String, String> params) throws Exception;


	/**
     * getPlayInfo.
     *
     * @param input com.bytedanceapi.model.vod.request.VodGetPlayInfoRequest
     * @return com.bytedanceapi.model.vod.response.VodGetPlayInfoResponse
     * @throws Exception the exception
     */
	com.bytedanceapi.model.vod.response.VodGetPlayInfoResponse getPlayInfo(com.bytedanceapi.model.vod.request.VodGetPlayInfoRequest input) throws Exception;
	
	/**
     * getOriginalPlayInfo.
     *
     * @param input com.bytedanceapi.model.vod.request.VodGetOriginalPlayInfoRequest
     * @return com.bytedanceapi.model.vod.response.VodGetOriginalPlayInfoResponse
     * @throws Exception the exception
     */
	com.bytedanceapi.model.vod.response.VodGetOriginalPlayInfoResponse getOriginalPlayInfo(com.bytedanceapi.model.vod.request.VodGetOriginalPlayInfoRequest input) throws Exception;
	
	/**
     * uploadMediaByUrl.
     *
     * @param input com.bytedanceapi.model.vod.request.VodUrlUploadRequest
     * @return com.bytedanceapi.model.vod.response.VodUrlUploadResponse
     * @throws Exception the exception
     */
	com.bytedanceapi.model.vod.response.VodUrlUploadResponse uploadMediaByUrl(com.bytedanceapi.model.vod.request.VodUrlUploadRequest input) throws Exception;
	
	/**
     * queryUploadTaskInfo.
     *
     * @param input com.bytedanceapi.model.vod.request.VodQueryUploadTaskInfoRequest
     * @return com.bytedanceapi.model.vod.response.VodQueryUploadTaskInfoResponse
     * @throws Exception the exception
     */
	com.bytedanceapi.model.vod.response.VodQueryUploadTaskInfoResponse queryUploadTaskInfo(com.bytedanceapi.model.vod.request.VodQueryUploadTaskInfoRequest input) throws Exception;
	
	/**
     * applyUploadInfo.
     *
     * @param input com.bytedanceapi.model.vod.request.VodApplyUploadInfoRequest
     * @return com.bytedanceapi.model.vod.response.VodApplyUploadInfoResponse
     * @throws Exception the exception
     */
	com.bytedanceapi.model.vod.response.VodApplyUploadInfoResponse applyUploadInfo(com.bytedanceapi.model.vod.request.VodApplyUploadInfoRequest input) throws Exception;
	
	/**
     * commitUploadInfo.
     *
     * @param input com.bytedanceapi.model.vod.request.VodCommitUploadInfoRequest
     * @return com.bytedanceapi.model.vod.response.VodCommitUploadInfoResponse
     * @throws Exception the exception
     */
	com.bytedanceapi.model.vod.response.VodCommitUploadInfoResponse commitUploadInfo(com.bytedanceapi.model.vod.request.VodCommitUploadInfoRequest input) throws Exception;
	
	/**
     * updateVideoInfo.
     *
     * @param input com.bytedanceapi.model.vod.request.VodUpdateVideoInfoRequest
     * @return com.bytedanceapi.model.vod.response.VodUpdateVideoInfoResponse
     * @throws Exception the exception
     */
	com.bytedanceapi.model.vod.response.VodUpdateVideoInfoResponse updateVideoInfo(com.bytedanceapi.model.vod.request.VodUpdateVideoInfoRequest input) throws Exception;
	
	/**
     * updateVideoPublishStatus.
     *
     * @param input com.bytedanceapi.model.vod.request.VodUpdateVideoPublishStatusRequest
     * @return com.bytedanceapi.model.vod.response.VodUpdateVideoPublishStatusResponse
     * @throws Exception the exception
     */
	com.bytedanceapi.model.vod.response.VodUpdateVideoPublishStatusResponse updateVideoPublishStatus(com.bytedanceapi.model.vod.request.VodUpdateVideoPublishStatusRequest input) throws Exception;
	
	/**
     * getVideoInfos.
     *
     * @param input com.bytedanceapi.model.vod.request.VodGetVideoInfosRequest
     * @return com.bytedanceapi.model.vod.response.VodGetVideoInfosResponse
     * @throws Exception the exception
     */
	com.bytedanceapi.model.vod.response.VodGetVideoInfosResponse getVideoInfos(com.bytedanceapi.model.vod.request.VodGetVideoInfosRequest input) throws Exception;
	
	/**
     * getRecommendedPoster.
     *
     * @param input com.bytedanceapi.model.vod.request.VodGetRecommendedPosterRequest
     * @return com.bytedanceapi.model.vod.response.VodGetRecommendedPosterResponse
     * @throws Exception the exception
     */
	com.bytedanceapi.model.vod.response.VodGetRecommendedPosterResponse getRecommendedPoster(com.bytedanceapi.model.vod.request.VodGetRecommendedPosterRequest input) throws Exception;
	
	/**
     * StartWorkflow.
     *
     * @param input com.bytedanceapi.model.vod.request.VodStartWorkflowRequest
     * @return com.bytedanceapi.model.vod.response.VodStartWorkflowResponse
     * @throws Exception the exception
     */
	com.bytedanceapi.model.vod.response.VodStartWorkflowResponse StartWorkflow(com.bytedanceapi.model.vod.request.VodStartWorkflowRequest input) throws Exception;
	
}  // end of service interface
