
// Code generated by protoc-gen-volcengine-sdk
// source: vod/service/service_vod.proto
// DO NOT EDIT!

package com.bytedanceapi.service.vod.impl;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.google.protobuf.StringValue;
import com.google.protobuf.util.JsonFormat;
import org.apache.http.NameValuePair;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.InputStreamReader;
import java.util.*;

public class VodServiceImpl extends com.bytedanceapi.service.BaseServiceImpl implements com.bytedanceapi.service.vod.IVodService {
	
	private VodServiceImpl() {
        super(com.bytedanceapi.service.vod.VodConfig.ServiceInfoMap.get(com.bytedanceapi.helper.Const.REGION_CN_NORTH_1), com.bytedanceapi.service.vod.VodConfig.apiInfoList);
    }

    private VodServiceImpl(com.bytedanceapi.model.ServiceInfo serviceInfo) {
        super(serviceInfo, com.bytedanceapi.service.vod.VodConfig.apiInfoList);
    }

    public static com.bytedanceapi.service.vod.IVodService getInstance() {
        return new VodServiceImpl();
    }

    public static com.bytedanceapi.service.vod.IVodService getInstance(String region) throws Exception {
        com.bytedanceapi.model.ServiceInfo serviceInfo = com.bytedanceapi.service.vod.VodConfig.ServiceInfoMap.get(region);
        if (serviceInfo == null) {
            throw new Exception("Cant find the region, please check it carefully");
        }
        return new VodServiceImpl(serviceInfo);
    }

	public com.bytedanceapi.model.sts2.SecurityToken2 getVideoPlayAuthWithExpiredTime(List<String> vidList, List<String> streamTypeList, List<String> watermarkList, long expiredTime) throws Exception {
        com.bytedanceapi.model.sts2.Policy inlinePolicy = new com.bytedanceapi.model.sts2.Policy();
        List<String> actions = new ArrayList<>();
        actions.add(com.bytedanceapi.service.vod.VodConfig.ACTION_GET_PLAY_INFO);
        List<String> resources = new ArrayList<>();

        // 设置vid的resource权限
        addResourceFormat(vidList, resources, com.bytedanceapi.service.vod.VodConfig.RESOURCE_VIDEO_FORMAT);

        // 设置streamType的resource权限
        addResourceFormat(streamTypeList, resources, com.bytedanceapi.service.vod.VodConfig.RESOURCE_STREAM_TYPE_FORMAT);

        // 设置watermark的resource权限
        addResourceFormat(watermarkList, resources, com.bytedanceapi.service.vod.VodConfig.RESOURCE_WATERMARK_FORMAT);

        com.bytedanceapi.model.sts2.Statement statement = com.bytedanceapi.util.Sts2Utils.newAllowStatement(actions, resources);
        inlinePolicy.addStatement(statement);
        return signSts2(inlinePolicy, expiredTime);
    }

    private void addResourceFormat(List<String> list, List<String> resources, String resourceFormat) {
        if (list.size() == 0)
            resources.add(String.format(resourceFormat, com.bytedanceapi.service.vod.VodConfig.STAR));
        else
            list.forEach(value -> resources.add(String.format(resourceFormat, value)));
    }

    public com.bytedanceapi.model.sts2.SecurityToken2 getVideoPlayAuth(List<String> vidList, List<String> streamTypeList, List<String> watermarkList) throws Exception {
        return getVideoPlayAuthWithExpiredTime(vidList, streamTypeList, watermarkList, com.bytedanceapi.util.Time.Hour);
    }


    private com.bytedanceapi.model.beans.UploadCompleteInfo upload(String spaceName, String filePath, String fileType) throws Exception {
        File file = new File(filePath);
        if (!(file.isFile() && file.exists())) {
            throw new Exception(com.bytedanceapi.error.SdkError.getErrorDesc(com.bytedanceapi.error.SdkError.ENOFILE));
        }
        long crc32 = com.bytedanceapi.helper.Utils.crc32(filePath);
        if (crc32 == -1) {
            throw new Exception("file crc32 error");
        }
        String checkSum = String.format("%x", crc32);

        com.bytedanceapi.model.vod.request.VodApplyUploadInfoRequest.Builder applyUploadRequest = com.bytedanceapi.model.vod.request.VodApplyUploadInfoRequest.newBuilder();
        applyUploadRequest.setSpaceName(spaceName);

        // apply upload
        com.bytedanceapi.model.vod.response.VodApplyUploadInfoResponse applyUploadResponse = applyUploadInfo(applyUploadRequest.build());
        if (applyUploadResponse.getResponseMetadata().getError() != null) {
            throw new Exception(applyUploadResponse.getResponseMetadata().getError().getMessage());
        }
        if (applyUploadResponse.getResult() == null || applyUploadResponse.getResult().getData().getUploadAddress().getStoreInfosList() == null) {
            throw new Exception("apply upload result is null");
        }

        String oid = applyUploadResponse.getResult().getData().getUploadAddress().getStoreInfos(0).getStoreUri();
        String sessionKey = applyUploadResponse.getResult().getData().getUploadAddress().getSessionKey();
        String auth = applyUploadResponse.getResult().getData().getUploadAddress().getStoreInfos(0).getAuth();
        String host = applyUploadResponse.getResult().getData().getUploadAddress().getUploadHosts(0);
        String url = String.format("http://%s/%s", host, oid);

        Map<String, String> headers = new HashMap<>();
        headers.put("Content-CRC32", checkSum);
        headers.put("Authorization", auth);

        long startTime = System.currentTimeMillis();
        boolean uploadStatus = false;
        for (int i = 0; i < 3; i++) {
            uploadStatus = put(url, filePath, headers);
            if (uploadStatus) {
                break;
            }
        }
        if (!uploadStatus) {
            throw new Exception(com.bytedanceapi.error.SdkError.getErrorDesc(com.bytedanceapi.error.SdkError.EUPLOAD));
        }
        long endTime = System.currentTimeMillis();
        long cost = endTime - startTime;
        float avgSpeed = (float) file.length() / (float) cost;
        System.out.println(String.format("upload {%s} cost {%d} ms, avgSpeed: {%f} KB/s", filePath, cost, avgSpeed));

        com.bytedanceapi.model.beans.UploadCompleteInfo uploadCompleteInfo = new com.bytedanceapi.model.beans.UploadCompleteInfo(oid, sessionKey);
        return uploadCompleteInfo;
    }


	@Override
    public String getPlayAuthToken(Map<String, String> params) throws Exception {
        Map<String, String> ret = new HashMap<>();
        ret.put("Version", "v1");
        String getPlayInfoToken = getSignUrl(com.bytedanceapi.helper.Const.GetPlayInfo, com.bytedanceapi.helper.Utils.mapToPairList(params));
        ret.put("GetPlayInfoToken", getPlayInfoToken);

        String retStr = JSON.toJSONString(ret);
        Base64.Encoder encoder = Base64.getEncoder();
        return encoder.encodeToString(retStr.getBytes());
    }

    @Override
    public String getUploadAuthToken(Map<String, String> params) throws Exception {
        Map<String, String> ret = new HashMap<String, String>();
        ret.put("Version", "v1");
        List<NameValuePair> pairs = com.bytedanceapi.helper.Utils.mapToPairList(params);

        String applyUploadToken = getSignUrl(com.bytedanceapi.helper.Const.ApplyUploadInfo, pairs);
        ret.put("ApplyUploadToken", applyUploadToken);

        String commitUploadToken = getSignUrl(com.bytedanceapi.helper.Const.CommitUploadInfo, pairs);
        ret.put("CommitUploadToken", commitUploadToken);

        String retStr = JSON.toJSONString(ret);
        Base64.Encoder encoder = Base64.getEncoder();
        return encoder.encodeToString(retStr.getBytes());
    }


	/**
     * getPlayInfo.
     *
     * @param input com.bytedanceapi.model.vod.request.VodGetPlayInfoRequest
     * @return com.bytedanceapi.model.vod.response.VodGetPlayInfoResponse
     * @throws Exception the exception
     */
	@Override
	public com.bytedanceapi.model.vod.response.VodGetPlayInfoResponse getPlayInfo(com.bytedanceapi.model.vod.request.VodGetPlayInfoRequest input) throws Exception {
		com.bytedanceapi.model.response.RawResponse response = query(com.bytedanceapi.helper.Const.GetPlayInfo, com.bytedanceapi.helper.Utils.mapToPairList(com.bytedanceapi.helper.Utils.protoBufferToMap(input)));
        if (response.getCode() != com.bytedanceapi.error.SdkError.SUCCESS.getNumber()) {
            throw response.getException();
        }
        com.bytedanceapi.model.vod.response.VodGetPlayInfoResponse.Builder responseBuilder = com.bytedanceapi.model.vod.response.VodGetPlayInfoResponse.newBuilder();
        JsonFormat.parser().ignoringUnknownFields().merge(new InputStreamReader(new ByteArrayInputStream(response.getData())), responseBuilder);
        return responseBuilder.build();
	}
	
	
	/**
     * getOriginalPlayInfo.
     *
     * @param input com.bytedanceapi.model.vod.request.VodGetOriginalPlayInfoRequest
     * @return com.bytedanceapi.model.vod.response.VodGetOriginalPlayInfoResponse
     * @throws Exception the exception
     */
	@Override
	public com.bytedanceapi.model.vod.response.VodGetOriginalPlayInfoResponse getOriginalPlayInfo(com.bytedanceapi.model.vod.request.VodGetOriginalPlayInfoRequest input) throws Exception {
		com.bytedanceapi.model.response.RawResponse response = query(com.bytedanceapi.helper.Const.GetOriginalPlayInfo, com.bytedanceapi.helper.Utils.mapToPairList(com.bytedanceapi.helper.Utils.protoBufferToMap(input)));
        if (response.getCode() != com.bytedanceapi.error.SdkError.SUCCESS.getNumber()) {
            throw response.getException();
        }
        com.bytedanceapi.model.vod.response.VodGetOriginalPlayInfoResponse.Builder responseBuilder = com.bytedanceapi.model.vod.response.VodGetOriginalPlayInfoResponse.newBuilder();
        JsonFormat.parser().ignoringUnknownFields().merge(new InputStreamReader(new ByteArrayInputStream(response.getData())), responseBuilder);
        return responseBuilder.build();
	}
	
	
	/**
     * uploadMediaByUrl.
     *
     * @param input com.bytedanceapi.model.vod.request.VodUrlUploadRequest
     * @return com.bytedanceapi.model.vod.response.VodUrlUploadResponse
     * @throws Exception the exception
     */
	@Override
	public com.bytedanceapi.model.vod.response.VodUrlUploadResponse uploadMediaByUrl(com.bytedanceapi.model.vod.request.VodUrlUploadRequest input) throws Exception {
        com.bytedanceapi.model.response.RawResponse response = query(com.bytedanceapi.helper.Const.UploadMediaByUrl, com.bytedanceapi.helper.Utils.mapToPairList(com.bytedanceapi.helper.Utils.protoBufferToMap(input)));
        if (response.getCode() != com.bytedanceapi.error.SdkError.SUCCESS.getNumber()) {
            throw response.getException();
        }
        com.bytedanceapi.model.vod.response.VodUrlUploadResponse.Builder responseBuilder = com.bytedanceapi.model.vod.response.VodUrlUploadResponse.newBuilder();
        JsonFormat.parser().ignoringUnknownFields().merge(new InputStreamReader(new ByteArrayInputStream(response.getData())), responseBuilder);
        return responseBuilder.build();
	}
	
	
	/**
     * queryUploadTaskInfo.
     *
     * @param input com.bytedanceapi.model.vod.request.VodQueryUploadTaskInfoRequest
     * @return com.bytedanceapi.model.vod.response.VodQueryUploadTaskInfoResponse
     * @throws Exception the exception
     */
	@Override
	public com.bytedanceapi.model.vod.response.VodQueryUploadTaskInfoResponse queryUploadTaskInfo(com.bytedanceapi.model.vod.request.VodQueryUploadTaskInfoRequest input) throws Exception {
		com.bytedanceapi.model.response.RawResponse response = query(com.bytedanceapi.helper.Const.QueryUploadTaskInfo, com.bytedanceapi.helper.Utils.mapToPairList(com.bytedanceapi.helper.Utils.protoBufferToMap(input)));
        if (response.getCode() != com.bytedanceapi.error.SdkError.SUCCESS.getNumber()) {
            throw response.getException();
        }
        com.bytedanceapi.model.vod.response.VodQueryUploadTaskInfoResponse.Builder responseBuilder = com.bytedanceapi.model.vod.response.VodQueryUploadTaskInfoResponse.newBuilder();
        JsonFormat.parser().ignoringUnknownFields().merge(new InputStreamReader(new ByteArrayInputStream(response.getData())), responseBuilder);
        return responseBuilder.build();
	}
	
	
	/**
     * applyUploadInfo.
     *
     * @param input com.bytedanceapi.model.vod.request.VodApplyUploadInfoRequest
     * @return com.bytedanceapi.model.vod.response.VodApplyUploadInfoResponse
     * @throws Exception the exception
     */
	@Override
	public com.bytedanceapi.model.vod.response.VodApplyUploadInfoResponse applyUploadInfo(com.bytedanceapi.model.vod.request.VodApplyUploadInfoRequest input) throws Exception {
		com.bytedanceapi.model.response.RawResponse response = query(com.bytedanceapi.helper.Const.ApplyUploadInfo, com.bytedanceapi.helper.Utils.mapToPairList(com.bytedanceapi.helper.Utils.protoBufferToMap(input)));
        if (response.getCode() != com.bytedanceapi.error.SdkError.SUCCESS.getNumber()) {
            throw response.getException();
        }
        com.bytedanceapi.model.vod.response.VodApplyUploadInfoResponse.Builder responseBuilder = com.bytedanceapi.model.vod.response.VodApplyUploadInfoResponse.newBuilder();
        JsonFormat.parser().ignoringUnknownFields().merge(new InputStreamReader(new ByteArrayInputStream(response.getData())), responseBuilder);
        return responseBuilder.build();
	}
	
	
	/**
     * commitUploadInfo.
     *
     * @param input com.bytedanceapi.model.vod.request.VodCommitUploadInfoRequest
     * @return com.bytedanceapi.model.vod.response.VodCommitUploadInfoResponse
     * @throws Exception the exception
     */
	@Override
	public com.bytedanceapi.model.vod.response.VodCommitUploadInfoResponse commitUploadInfo(com.bytedanceapi.model.vod.request.VodCommitUploadInfoRequest input) throws Exception {
		com.bytedanceapi.model.response.RawResponse response = query(com.bytedanceapi.helper.Const.CommitUploadInfo, com.bytedanceapi.helper.Utils.mapToPairList(com.bytedanceapi.helper.Utils.protoBufferToMap(input)));
        if (response.getCode() != com.bytedanceapi.error.SdkError.SUCCESS.getNumber()) {
            throw response.getException();
        }
        com.bytedanceapi.model.vod.response.VodCommitUploadInfoResponse.Builder responseBuilder = com.bytedanceapi.model.vod.response.VodCommitUploadInfoResponse.newBuilder();
        JsonFormat.parser().ignoringUnknownFields().merge(new InputStreamReader(new ByteArrayInputStream(response.getData())), responseBuilder);
        return responseBuilder.build();
	}
	
	
	/**
     * updateVideoInfo.
     *
     * @param input com.bytedanceapi.model.vod.request.VodUpdateVideoInfoRequest
     * @return com.bytedanceapi.model.vod.response.VodUpdateVideoInfoResponse
     * @throws Exception the exception
     */
	@Override
	public com.bytedanceapi.model.vod.response.VodUpdateVideoInfoResponse updateVideoInfo(com.bytedanceapi.model.vod.request.VodUpdateVideoInfoRequest input) throws Exception {
		com.bytedanceapi.model.response.RawResponse response = query(com.bytedanceapi.helper.Const.UpdateVideoInfo, com.bytedanceapi.helper.Utils.mapToPairList(com.bytedanceapi.helper.Utils.protoBufferToMap(input)));
        if (response.getCode() != com.bytedanceapi.error.SdkError.SUCCESS.getNumber()) {
            throw response.getException();
        }
        com.bytedanceapi.model.vod.response.VodUpdateVideoInfoResponse.Builder responseBuilder = com.bytedanceapi.model.vod.response.VodUpdateVideoInfoResponse.newBuilder();
        JsonFormat.parser().ignoringUnknownFields().merge(new InputStreamReader(new ByteArrayInputStream(response.getData())), responseBuilder);
        return responseBuilder.build();
	}
	
	
	/**
     * updateVideoPublishStatus.
     *
     * @param input com.bytedanceapi.model.vod.request.VodUpdateVideoPublishStatusRequest
     * @return com.bytedanceapi.model.vod.response.VodUpdateVideoPublishStatusResponse
     * @throws Exception the exception
     */
	@Override
	public com.bytedanceapi.model.vod.response.VodUpdateVideoPublishStatusResponse updateVideoPublishStatus(com.bytedanceapi.model.vod.request.VodUpdateVideoPublishStatusRequest input) throws Exception {
		com.bytedanceapi.model.response.RawResponse response = query(com.bytedanceapi.helper.Const.UpdateVideoPublishStatus, com.bytedanceapi.helper.Utils.mapToPairList(com.bytedanceapi.helper.Utils.protoBufferToMap(input)));
        if (response.getCode() != com.bytedanceapi.error.SdkError.SUCCESS.getNumber()) {
            throw response.getException();
        }
        com.bytedanceapi.model.vod.response.VodUpdateVideoPublishStatusResponse.Builder responseBuilder = com.bytedanceapi.model.vod.response.VodUpdateVideoPublishStatusResponse.newBuilder();
        JsonFormat.parser().ignoringUnknownFields().merge(new InputStreamReader(new ByteArrayInputStream(response.getData())), responseBuilder);
        return responseBuilder.build();
	}
	
	
	/**
     * getVideoInfos.
     *
     * @param input com.bytedanceapi.model.vod.request.VodGetVideoInfosRequest
     * @return com.bytedanceapi.model.vod.response.VodGetVideoInfosResponse
     * @throws Exception the exception
     */
	@Override
	public com.bytedanceapi.model.vod.response.VodGetVideoInfosResponse getVideoInfos(com.bytedanceapi.model.vod.request.VodGetVideoInfosRequest input) throws Exception {
		com.bytedanceapi.model.response.RawResponse response = query(com.bytedanceapi.helper.Const.GetVideoInfos, com.bytedanceapi.helper.Utils.mapToPairList(com.bytedanceapi.helper.Utils.protoBufferToMap(input)));
        if (response.getCode() != com.bytedanceapi.error.SdkError.SUCCESS.getNumber()) {
            throw response.getException();
        }
        com.bytedanceapi.model.vod.response.VodGetVideoInfosResponse.Builder responseBuilder = com.bytedanceapi.model.vod.response.VodGetVideoInfosResponse.newBuilder();
        JsonFormat.parser().ignoringUnknownFields().merge(new InputStreamReader(new ByteArrayInputStream(response.getData())), responseBuilder);
        return responseBuilder.build();
	}
	
	
	/**
     * getRecommendedPoster.
     *
     * @param input com.bytedanceapi.model.vod.request.VodGetRecommendedPosterRequest
     * @return com.bytedanceapi.model.vod.response.VodGetRecommendedPosterResponse
     * @throws Exception the exception
     */
	@Override
	public com.bytedanceapi.model.vod.response.VodGetRecommendedPosterResponse getRecommendedPoster(com.bytedanceapi.model.vod.request.VodGetRecommendedPosterRequest input) throws Exception {
		com.bytedanceapi.model.response.RawResponse response = query(com.bytedanceapi.helper.Const.GetRecommendedPoster, com.bytedanceapi.helper.Utils.mapToPairList(com.bytedanceapi.helper.Utils.protoBufferToMap(input)));
        if (response.getCode() != com.bytedanceapi.error.SdkError.SUCCESS.getNumber()) {
            throw response.getException();
        }
        com.bytedanceapi.model.vod.response.VodGetRecommendedPosterResponse.Builder responseBuilder = com.bytedanceapi.model.vod.response.VodGetRecommendedPosterResponse.newBuilder();
        JsonFormat.parser().ignoringUnknownFields().merge(new InputStreamReader(new ByteArrayInputStream(response.getData())), responseBuilder);
        return responseBuilder.build();
	}
	
	
	/**
     * StartWorkflow.
     *
     * @param input com.bytedanceapi.model.vod.request.VodStartWorkflowRequest
     * @return com.bytedanceapi.model.vod.response.VodStartWorkflowResponse
     * @throws Exception the exception
     */
	@Override
	public com.bytedanceapi.model.vod.response.VodStartWorkflowResponse StartWorkflow(com.bytedanceapi.model.vod.request.VodStartWorkflowRequest input) throws Exception {
		com.bytedanceapi.model.response.RawResponse response = query(com.bytedanceapi.helper.Const.StartWorkflow, com.bytedanceapi.helper.Utils.mapToPairList(com.bytedanceapi.helper.Utils.protoBufferToMap(input)));
        if (response.getCode() != com.bytedanceapi.error.SdkError.SUCCESS.getNumber()) {
            throw response.getException();
        }
        com.bytedanceapi.model.vod.response.VodStartWorkflowResponse.Builder responseBuilder = com.bytedanceapi.model.vod.response.VodStartWorkflowResponse.newBuilder();
        JsonFormat.parser().ignoringUnknownFields().merge(new InputStreamReader(new ByteArrayInputStream(response.getData())), responseBuilder);
        return responseBuilder.build();
	}
	
	
}  // end of service interface
