// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod/business/vod_upload.proto

package com.bytedanceapi.model.vod.business;

public interface CommitDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Vcloud.Models.Vod.CommitData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Vcloud.Models.Vod.CommitUploadInfoResponse Data = 1;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.Vcloud.Models.Vod.CommitUploadInfoResponse Data = 1;</code>
   * @return The data.
   */
  CommitUploadInfoResponse getData();
  /**
   * <code>.Vcloud.Models.Vod.CommitUploadInfoResponse Data = 1;</code>
   */
  CommitUploadInfoResponseOrBuilder getDataOrBuilder();
}
