// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod/business/vod_upload.proto

package com.bytedanceapi.model.vod.business;

public interface EncryptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Vcloud.Models.Vod.Encryption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Uri = 1;</code>
   * @return The uri.
   */
  java.lang.String getUri();
  /**
   * <code>string Uri = 1;</code>
   * @return The bytes for uri.
   */
  com.google.protobuf.ByteString
      getUriBytes();

  /**
   * <code>string SecretKey = 2;</code>
   * @return The secretKey.
   */
  java.lang.String getSecretKey();
  /**
   * <code>string SecretKey = 2;</code>
   * @return The bytes for secretKey.
   */
  com.google.protobuf.ByteString
      getSecretKeyBytes();

  /**
   * <code>string Algorithm = 3;</code>
   * @return The algorithm.
   */
  java.lang.String getAlgorithm();
  /**
   * <code>string Algorithm = 3;</code>
   * @return The bytes for algorithm.
   */
  com.google.protobuf.ByteString
      getAlgorithmBytes();

  /**
   * <code>string Version = 4;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string Version = 4;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string SourceMD5 = 5;</code>
   * @return The sourceMD5.
   */
  java.lang.String getSourceMD5();
  /**
   * <code>string SourceMD5 = 5;</code>
   * @return The bytes for sourceMD5.
   */
  com.google.protobuf.ByteString
      getSourceMD5Bytes();
}
