// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod/business/vod_upload.proto

package com.bytedanceapi.model.vod.business;

public interface VodApplyUploadInfoDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Vcloud.Models.Vod.VodApplyUploadInfoData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Vcloud.Models.Vod.VodUploadAddress UploadAddress = 1;</code>
   * @return Whether the uploadAddress field is set.
   */
  boolean hasUploadAddress();
  /**
   * <code>.Vcloud.Models.Vod.VodUploadAddress UploadAddress = 1;</code>
   * @return The uploadAddress.
   */
  com.bytedanceapi.model.vod.business.VodUploadAddress getUploadAddress();
  /**
   * <code>.Vcloud.Models.Vod.VodUploadAddress UploadAddress = 1;</code>
   */
  com.bytedanceapi.model.vod.business.VodUploadAddressOrBuilder getUploadAddressOrBuilder();
}
