// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod/business/vod_media.proto

package com.bytedanceapi.model.vod.business;

public interface VodGetVideoInfosDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Vcloud.Models.Vod.VodGetVideoInfosData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *视频信息列表
   * </pre>
   *
   * <code>repeated .Vcloud.Models.Vod.VodVideoInfo VideoInfoList = 1;</code>
   */
  java.util.List<VodVideoInfo>
      getVideoInfoListList();
  /**
   * <pre>
   *视频信息列表
   * </pre>
   *
   * <code>repeated .Vcloud.Models.Vod.VodVideoInfo VideoInfoList = 1;</code>
   */
  VodVideoInfo getVideoInfoList(int index);
  /**
   * <pre>
   *视频信息列表
   * </pre>
   *
   * <code>repeated .Vcloud.Models.Vod.VodVideoInfo VideoInfoList = 1;</code>
   */
  int getVideoInfoListCount();
  /**
   * <pre>
   *视频信息列表
   * </pre>
   *
   * <code>repeated .Vcloud.Models.Vod.VodVideoInfo VideoInfoList = 1;</code>
   */
  java.util.List<? extends VodVideoInfoOrBuilder>
      getVideoInfoListOrBuilderList();
  /**
   * <pre>
   *视频信息列表
   * </pre>
   *
   * <code>repeated .Vcloud.Models.Vod.VodVideoInfo VideoInfoList = 1;</code>
   */
  VodVideoInfoOrBuilder getVideoInfoListOrBuilder(
      int index);

  /**
   * <pre>
   *不存在的视频VID列表
   * </pre>
   *
   * <code>repeated string NotExistVids = 2;</code>
   * @return A list containing the notExistVids.
   */
  java.util.List<java.lang.String>
      getNotExistVidsList();
  /**
   * <pre>
   *不存在的视频VID列表
   * </pre>
   *
   * <code>repeated string NotExistVids = 2;</code>
   * @return The count of notExistVids.
   */
  int getNotExistVidsCount();
  /**
   * <pre>
   *不存在的视频VID列表
   * </pre>
   *
   * <code>repeated string NotExistVids = 2;</code>
   * @param index The index of the element to return.
   * @return The notExistVids at the given index.
   */
  java.lang.String getNotExistVids(int index);
  /**
   * <pre>
   *不存在的视频VID列表
   * </pre>
   *
   * <code>repeated string NotExistVids = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the notExistVids at the given index.
   */
  com.google.protobuf.ByteString
      getNotExistVidsBytes(int index);
}
