// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod/business/vod_play.proto

package com.bytedanceapi.model.vod.business;

public final class VodPlay {
  private VodPlay() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vcloud_Models_Vod_VodGetPlayInfoResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Vcloud_Models_Vod_VodGetPlayInfoResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vcloud_Models_Vod_VodGetOriginalPlayInfoResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Vcloud_Models_Vod_VodGetOriginalPlayInfoResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033vod/business/vod_play.proto\022\021Vcloud.Mo" +
      "dels.Vod\032\035vod/business/vod_common.proto\"" +
      "\206\002\n\024VodGetPlayInfoResult\022\013\n\003Vid\030\001 \001(\t\022\016\n" +
      "\006Status\030\002 \001(\003\022\021\n\tPosterUrl\030\003 \001(\t\022\020\n\010Dura" +
      "tion\030\004 \001(\002\022\020\n\010FileType\030\005 \001(\t\022\026\n\016EnableAd" +
      "aptive\030\006 \001(\010\022\022\n\nTotalCount\030\007 \001(\003\0228\n\014Adap" +
      "tiveInfo\030\010 \001(\0132\".Vcloud.Models.Vod.VodAd" +
      "aptiveInfo\0224\n\014PlayInfoList\030\t \003(\0132\036.Vclou" +
      "d.Models.Vod.VodPlayInfo\"\330\001\n\034VodGetOrigi" +
      "nalPlayInfoResult\022\020\n\010FileType\030\001 \001(\t\022\020\n\010D" +
      "uration\030\002 \001(\002\022\014\n\004Size\030\003 \001(\003\022\016\n\006Height\030\004 " +
      "\001(\003\022\r\n\005Width\030\005 \001(\003\022\016\n\006Format\030\006 \001(\t\022\r\n\005Co" +
      "dec\030\007 \001(\t\022\017\n\007Bitrate\030\010 \001(\002\022\013\n\003Md5\030\t \001(\t\022" +
      "\023\n\013MainPlayUrl\030\n \001(\t\022\025\n\rBackupPlayUrl\030\013 " +
      "\001(\tB\255\001\n#com.bytedanceapi.model.vod.busin" +
      "essB\007VodPlayP\001Z9github.com/volcengine/vo" +
      "lc-sdk-golang/models/vod/business\240\001\001\330\001\001\302" +
      "\002\000\312\002\032Vcloud\\Models\\Vod\\Business\342\002\031Vcloud" +
      "\\Models\\GPBMetadatab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bytedanceapi.model.vod.business.VodCommon.getDescriptor(),
        });
    internal_static_Vcloud_Models_Vod_VodGetPlayInfoResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Vcloud_Models_Vod_VodGetPlayInfoResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Vcloud_Models_Vod_VodGetPlayInfoResult_descriptor,
        new java.lang.String[] { "Vid", "Status", "PosterUrl", "Duration", "FileType", "EnableAdaptive", "TotalCount", "AdaptiveInfo", "PlayInfoList", });
    internal_static_Vcloud_Models_Vod_VodGetOriginalPlayInfoResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Vcloud_Models_Vod_VodGetOriginalPlayInfoResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Vcloud_Models_Vod_VodGetOriginalPlayInfoResult_descriptor,
        new java.lang.String[] { "FileType", "Duration", "Size", "Height", "Width", "Format", "Codec", "Bitrate", "Md5", "MainPlayUrl", "BackupPlayUrl", });
    com.bytedanceapi.model.vod.business.VodCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
