// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod/business/vod_upload.proto

package com.bytedanceapi.model.vod.business;

public interface VodQueryDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Vcloud.Models.Vod.VodQueryData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Vcloud.Models.Vod.VodQueryUploadResult Data = 1;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.Vcloud.Models.Vod.VodQueryUploadResult Data = 1;</code>
   * @return The data.
   */
  com.bytedanceapi.model.vod.business.VodQueryUploadResult getData();
  /**
   * <code>.Vcloud.Models.Vod.VodQueryUploadResult Data = 1;</code>
   */
  com.bytedanceapi.model.vod.business.VodQueryUploadResultOrBuilder getDataOrBuilder();
}
